Repository gdsfactory/gdsfactory, pull requests merged in 2023-11, with the labels that each got.

#2273 Pin versions
  pyproject.toml
Labels: dependencies

#2295 Update `gf install` command for KLayout integration
  docs/notebooks/_2_klayout.py
Labels: documentation

#2299 Fix `inspect.signature` bug for partials with partialed decorators
  gdsfactory/get_factories.py
Labels: bug

#2325 Improve docstrings for `add_pins`
  gdsfactory/add_pins.py
Labels: documentation
