Repository gdsfactory/gdsfactory, pull requests merged in 2024-04, with the labels that each got.

#2654 snap ports to grid
  README.md
  gdsfactory/components/add_grating_couplers.py
  gdsfactory/components/cutback_bend.py
  gdsfactory/components/delay_snake2.py
  gdsfactory/components/optimal_90deg.py
  gdsfactory/components/optimal_step.py
  gdsfactory/components/taper_adiabatic.py
Labels: documentation, maintenance

#2655 fix array ports
  gdsfactory/components/array_component.py
Labels: bug

#2657 [minor bugs] Port.info: shallow copy -> deep copy
  gdsfactory/port.py
Labels: maintenance

#2656 Obey stacklevel in `warnings.warn` for loguru output
  gdsfactory/config.py
Labels: python

#2658 Bugfix: make `Component.remap_layers` actually return a copy
  gdsfactory/component.py
Labels: bug

#2659 release-drafter workflow
  .github/workflows/release-drafter.yml
  .github/workflows/require-labels.yml
Labels: github_actions

#2661 allow custom import gds
  gdsfactory/cell.py
  gdsfactory/config.py
  tests/gds/thermal_phase_shifters.gds
  tests/test_import_gds.py
  tests/test_import_gds_cell2.py
Labels: maintenance

#2662 add flag to remap layers
  gdsfactory/component.py
Labels: enhancement

#2665 Fix cell decorator
  gdsfactory/cell.py
  gdsfactory/pdk.py
  gdsfactory/serialization.py
  tests/test_cache.py
  tests/test_components_serialize.py
Labels: bug

#2666 fix text justify
  gdsfactory/components/text.py
Labels: bug

#2668 fix cross_section for ring_single_bend_coupler
  gdsfactory/components/coupler_bent.py
  gdsfactory/components/ring_single_bend_coupler.py
  test-data-regression/test_settings_ring_single_bend_coupler_.yml
Labels: bug

#2679 improve updk
  gdsfactory/components/die.py
  gdsfactory/read/from_updk.py
Labels: maintenance

#2680 better import gds and ports
  gdsfactory/add_ports.py
  gdsfactory/read/import_gds.py
Labels: maintenance

#2681 fix docs
  pyproject.toml
Labels: bug

#2683 add component_with_function
  gdsfactory/__init__.py
  gdsfactory/cell.py
Labels: enhancement

#2685 remove fill_rectangle from docs
  notebooks/04_components_geometry.ipynb
Labels: maintenance

#2687 Improve component with function
  gdsfactory/cell.py
Labels: maintenance

#2692 Fix cell annotation
  gdsfactory/cell.py
  gdsfactory/components/straight.py
  test-data-regression/test_netlists_sample_connections_.yml
  test-data-regression/test_settings_tapers_.yml
  tests/test_paths_transition3.py
Labels: bug

#2694 Pdk improvements
  gdsfactory/components/ring_crow.py
  gdsfactory/components/spiral_double.py
  gdsfactory/generic_tech/simulation_settings.py
  test-data-regression/test_settings_ring_crow_.yml
  test-data-regression/test_settings_spiral_double_.yml
Labels: maintenance

#2696 import_gds unique names appends uuid
  gdsfactory/read/import_gds.py
  tests/test_component_pickle.py
  tests/test_import_gds2.py
Labels: bug

#2700 Rename fiber ports
  gdsfactory/components/edge_coupler_array.py
  gdsfactory/components/grating_coupler_elliptical.py
  gdsfactory/components/grating_coupler_elliptical_arbitrary.py
  gdsfactory/components/grating_coupler_elliptical_trenches.py
  gdsfactory/components/grating_coupler_rectangular.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary_slab.py
  test-data-regression/test_settings_edge_coupler_array_.yml
  test-data-regression/test_settings_edge_coupler_array_with_loopback_.yml
  test-data-regression/test_settings_edge_coupler_silicon_.yml
Labels: maintenance

#2702 fix stl export
  gdsfactory/export/to_stl.py
Labels: bug

#2701 Forbid width missmatch
  docs/components.rst
  gdsfactory/component.py
  gdsfactory/component_reference.py
  gdsfactory/components/array_with_fanout.py
  gdsfactory/components/array_with_via.py
  gdsfactory/components/coupler_full.py
  gdsfactory/components/dbr.py
  gdsfactory/components/edge_coupler_array.py
  gdsfactory/components/ge_detector_straight_si_contacts.py
  gdsfactory/components/greek_cross.py
  gdsfactory/components/optimal_hairpin.py
  gdsfactory/components/polarization_splitter_rotator.py
  gdsfactory/components/resistance_sheet.py
  gdsfactory/components/ring_crow_couplers.py
  gdsfactory/components/ring_double_pn.py
  gdsfactory/components/spiral_heater.py
  gdsfactory/components/straight_heater_meander.py
  gdsfactory/components/straight_heater_metal.py
  gdsfactory/components/taper.py
  gdsfactory/components/via_cutback.py
  gdsfactory/config.py
  gdsfactory/routing/get_routes_bend180.py
  gdsfactory/routing/get_routes_straight.py
  gdsfactory/routing/manhattan.py
  gdsfactory/technology/layer_views.py
  notebooks/00_geometry.ipynb
  notebooks/01_references.ipynb
  notebooks/04_routing.ipynb
  notebooks/04_routing_electrical.ipynb
  notebooks/rib_strip_autotransition.ipynb
  test-data-regression/test_netlists_mzit_.yml
  test-data-regression/test_settings_edge_coupler_array_.yml
  test-data-regression/test_settings_edge_coupler_array_with_loopback_.yml
  test-data-regression/test_settings_edge_coupler_silicon_.yml
  test-data-regression/test_settings_ring_crow_couplers_.yml
  test-data-regression/test_settings_taper2_.yml
  test-data-regression/test_settings_taper_.yml
  tests/routing/test_routing_get_route_sbend.py
  tests/test_component.py
Labels: enhancement

#2705 Bugfix in support info dicts
  gdsfactory/component_layout.py
Labels: maintenance

#2704 bugfix in manhattan routing if the first reference is a bend turn
  gdsfactory/routing/manhattan.py
Labels: bug

#2707 better docstrings
  gdsfactory/add_padding.py
  gdsfactory/components/ring_crow.py
Labels: documentation

#2709 Expose gc fiber port
  gdsfactory/components/straight_heater_metal.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/routing/route_fiber_single.py
  test-data-regression/test_settings_add_fiber_single_.yml
  tests/test_label_custom.py
Labels: bug
