Repository gdsfactory/gdsfactory, pull requests merged in 2024-07, with the labels that each got.

#2931 fix #2928
  gdsfactory/component.py
Labels: bug

#2937 allow_callable_width
  gdsfactory/path.py
Labels: bug

#2941 fixes ComponentAlongPath by making it frozen
  gdsfactory/cross_section.py
Labels: bug

#2942 Increase backwards compat
  gdsfactory/component.py
  gdsfactory/path.py
  gdsfactory/samples/pdk/test_fab_c/test_settings_mzi_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mzi_no_.yml
Labels: maintenance

#2948 More from yaml updates
  gdsfactory/__init__.py
  gdsfactory/cell.py
  gdsfactory/components/coupler.py
  gdsfactory/cross_section.py
  gdsfactory/read/from_yaml.py
  test-data-regression/test_netlists_coupler_.yml
  test-data-regression/test_netlists_mzit_.yml
  test-data-regression/test_netlists_ring_crow_couplers_.yml
  test-data-regression/test_settings_coupler_.yml
Labels: maintenance

#2951 fix extrude to work with transitions
  gdsfactory/path.py
  tests/test_path.py
Labels: bug

#2954 add gf.functions.get_point_inside
  gdsfactory/__init__.py
  gdsfactory/component.py
  gdsfactory/functions.py
Labels: enhancement

#2956 add cross_section to route_bundle_all_angle
  gdsfactory/routing/route_bundle_all_angle.py
Labels: enhancement

#2957 add component copy_layers
  gdsfactory/component.py
Labels: enhancement

#2958 Improve warnings traceback
  gdsfactory/component.py
  gdsfactory/components/bend_euler.py
Labels: maintenance, v7->v8

#2959 fix slabfix slab grating_coupler
  gdsfactory/components/grating_coupler_rectangular.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary.py
Labels: bug

#2960 improve die
  README.md
  gdsfactory/components/die_with_pads.py
  gdsfactory/components/grating_coupler_array.py
  test-data-regression/test_netlists_die_with_pads_.yml
  test-data-regression/test_settings_die_with_pads_.yml
Labels: documentation, maintenance

#2962 add Luxtelligence pdk logo
  README.md
Labels: documentation, enhancement

#2964 Add skrf
  gdsfactory/components/wafer.py
  notebooks/04_components_geometry.ipynb
  pyproject.toml
Labels: enhancement

#2967 add autograd
  pyproject.toml
Labels: enhancement, dependencies

#2970 Improve write cells and fix taper
  gdsfactory/add_ports.py
  gdsfactory/cli.py
  gdsfactory/components/spiral_double.py
  gdsfactory/components/taper.py
  gdsfactory/path.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/typings.py
  gdsfactory/write_cells.py
  notebooks/09_pdk_import.ipynb
  tests/test_add_ports.py
Labels: bug

#2971 modify route_bundle_sbend to accept customized s bend, adapt from route_single_sbend
  docs/notebooks
  gdsfactory/routing/route_bundle_sbend.py
Labels: maintenance

#2972 improve add_electrical_pads_top
  gdsfactory/routing/add_electrical_pads_top.py
Labels: bug

#2974 read from yaml: minor fixes
  gdsfactory/read/from_yaml.py
Labels: bug

#2975 fix mzi netlist and add cache to import_gds
  gdsfactory/read/import_gds.py
  test-data-regression/test_netlists_mzi_.yml
  tests/components/test_netlists.py
Labels: bug

#2977 improve docs
  README.md
  docs/api.rst
  docs/components.rst
  docs/logo.png
  docs/logo256x256.png
  gdsfactory/typings.py
Labels: documentation

#2982 remove import_gds cache
  gdsfactory/read/import_gds.py
Labels: maintenance

#2983 update kfactory to 0.18
  pyproject.toml
Labels: dependencies, github_actions

#2989 Improve route south
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/routing/route_south.py
  gdsfactory/samples/01_component_pcell_with_parameters.py
  gdsfactory/samples/big_device.py
  gdsfactory/samples/demo/drc_errors.py
  gdsfactory/samples/sample_mzis.py
  gdsfactory/samples/sample_reticle.py
Labels: maintenance

#2986 small change to allow `from_updk` to save `cross_section` name to `port.info`
  gdsfactory/read/from_updk.py
Labels: maintenance

#2993 check if radius is None
  gdsfactory/path.py
Labels: maintenance

#2994 support attrs serialization
  gdsfactory/serialization.py
Labels: bug

#2995 updatre readme
  CHANGELOG.md
  README.md
Labels: documentation

#3000 improve add_ports_from_labels
  README.md
  gdsfactory/add_ports.py
Labels: documentation, maintenance

#3001 Add fiber single
  gdsfactory/routing/__init__.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/routing/route_fiber_array.py
Labels: maintenance

#3003 Add move port to zero
  gdsfactory/functions.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/route_fiber_array.py
Labels: maintenance

#3004 fix straight_heater_metal_simple
  gdsfactory/components/straight_heater_metal.py
  gdsfactory/routing/route_single.py
  test-data-regression/test_netlists_straight_heater_metal_simple_.yml
Labels: bug

#3005 Simpler netlist
  gdsfactory/components/coupler.py
  gdsfactory/components/coupler90.py
  gdsfactory/components/coupler_asymmetric.py
  gdsfactory/components/coupler_ring.py
  gdsfactory/components/dicing_lane.py
  gdsfactory/components/ring_double.py
  gdsfactory/components/ring_heater.py
  gdsfactory/components/ring_single.py
  gdsfactory/components/seal_ring.py
  gdsfactory/components/via_stack.py
  gdsfactory/components/wire.py
  test-data-regression/test_netlists_coupler_.yml
  test-data-regression/test_netlists_coupler_asymmetric_.yml
  test-data-regression/test_netlists_coupler_ring_.yml
  test-data-regression/test_netlists_dicing_lane_.yml
  test-data-regression/test_netlists_mzit_.yml
  test-data-regression/test_netlists_pad_array0_.yml
  test-data-regression/test_netlists_pad_array90_.yml
  test-data-regression/test_netlists_ring_crow_couplers_.yml
  test-data-regression/test_netlists_ring_double_.yml
  test-data-regression/test_netlists_ring_double_heater_.yml
  test-data-regression/test_netlists_ring_single_.yml
  test-data-regression/test_netlists_ring_single_array_.yml
  test-data-regression/test_netlists_ring_single_dut_.yml
  test-data-regression/test_netlists_ring_single_heater_.yml
  test-data-regression/test_netlists_via_stack_.yml
  test-data-regression/test_netlists_via_stack_heater_m3_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_mini_.yml
  test-data-regression/test_netlists_via_stack_m1_mtop_.yml
  test-data-regression/test_netlists_via_stack_npp_m1_.yml
  test-data-regression/test_netlists_via_stack_slab_m1_horizontal_.yml
  test-data-regression/test_netlists_via_stack_slab_m3_.yml
  test-data-regression/test_settings_coupler_.yml
  test-data-regression/test_settings_coupler_asymmetric_.yml
  test-data-regression/test_settings_coupler_ring_.yml
  test-data-regression/test_settings_ring_double_.yml
  test-data-regression/test_settings_ring_single_.yml
  tests/components/test_netlists.py
Labels: maintenance

#3013 fix boolean.py
  gdsfactory/boolean.py
Labels: bug

#3017 Fix Path curvature failing for simple straights
  gdsfactory/path.py
Labels: bug

#3018 Pin kfactory
  gdsfactory/components/straight_heater_meander_doped.py
  pyproject.toml
  tests/test_add_ports.py
  tests/test_component.py
  tests/test_diff.py
Labels: dependencies

#3020 fix get_polygons for instances
  gdsfactory/functions.py
Labels: bug

#3024 default label instance
  gdsfactory/add_pins.py
Labels: maintenance

#3025 Removing omegaconf
  README.md
  gdsfactory/add_pins.py
  gdsfactory/component.py
  gdsfactory/labels/add_label_yaml.py
  gdsfactory/pdk.py
  gdsfactory/read/__init__.py
  gdsfactory/read/from_updk.py
  gdsfactory/read/from_yaml.py
  gdsfactory/read/labels.py
  gdsfactory/samples/netlists/straight_with_bend.yml
  gdsfactory/schematic.py
  gdsfactory/serialization.py
  gdsfactory/technology/layer_views.py
  notebooks/09_pdk_import.ipynb
  notebooks/10_schematic.ipynb
  pyproject.toml
  tests/components/test_netlists.py
  tests/read/test_updk.py
  tests/schemas/netlist.json
  tests/schemas/netlist.yaml
  tests/test_diff.py
Labels: documentation, enhancement, dependencies

#3031 fix dup
  gdsfactory/read/from_yaml_template.py
Labels: bug

#3030 Loosen pydantic version and add attrs to dependencies
  pyproject.toml
Labels: bug, dependencies

#3026 Use Literals for typing port side in routing
  gdsfactory/routing/route_ports_to_side.py
Labels: enhancement

#3032 Small tweaks in `add_pins`
  gdsfactory/add_pins.py
Labels: enhancement

#3034 simpler add_pins
  gdsfactory/add_pins.py
Labels: maintenance

#3043 Add mmi tapered
  gdsfactory/components/__init__.py
  gdsfactory/components/mmi_tapered.py
  gdsfactory/components/taper.py
  gdsfactory/samples/24_doe_2.py
  test-data-regression/test_netlists_mmi_tapered_.yml
  test-data-regression/test_settings_mmi_tapered_.yml
Labels: enhancement

#3044 add omegaconf to docker build
  pyproject.toml
Labels: enhancement, dependencies

#3046 Fix get polygons by tuple
  gdsfactory/component.py
  gdsfactory/functions.py
  gdsfactory/pdk.py
  notebooks/21_migration_guide_7_8.ipynb
  tests/test_functions.py
Labels: bug

#3047 add trim
  gdsfactory/functions.py
  tests/test_functions.py
Labels: enhancement

#3048 add trim in place
  gdsfactory/component.py
  gdsfactory/functions.py
  tests/test_component.py
Labels: enhancement

#3049 remove temp oasis files
  gdsfactory/component.py
  gdsfactory/read/import_gds.py
  tests/test_add_ports.py
Labels: bug

#3050 gf.functions.trim leverages hierarchical trim from Component.trim
  gdsfactory/functions.py
  tests/test_functions.py
Labels: maintenance

#3052 fix trim
  .codecov.yml
  gdsfactory/component.py
  gdsfactory/functions.py
  gdsfactory/serialization.py
  tests/test_functions.py
  tests/test_get_netlist_yaml.py
  tests/test_get_netlist_yaml2.py
  tests/test_get_netlist_yaml3.py
  tests/test_get_netlist_yaml4.py
  tests/test_get_netlist_yaml5.py
Labels: bug

#3064 use generic port names
  gdsfactory/components/bend_euler.py
  gdsfactory/components/coupler90.py
  gdsfactory/components/coupler_straight.py
  gdsfactory/components/coupler_straight_asymmetric.py
  gdsfactory/components/coupler_symmetric.py
  gdsfactory/components/mzi.py
  gdsfactory/samples/pdk/test_fab_c/test_settings_mzi_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mzi_no_.yml
  test-data-regression/test_netlists_bend_euler_s_.yml
  test-data-regression/test_netlists_coh_tx_single_pol_.yml
  test-data-regression/test_netlists_mzi1x2_2x2_.yml
  test-data-regression/test_netlists_mzi2x2_2x2_.yml
  test-data-regression/test_netlists_mzi2x2_2x2_phase_shifter_.yml
  test-data-regression/test_netlists_mzi_.yml
  test-data-regression/test_netlists_mzi_coupler_.yml
  test-data-regression/test_netlists_mzi_pads_center_.yml
  test-data-regression/test_netlists_mzi_phase_shifter_.yml
  test-data-regression/test_netlists_mzi_phase_shifter_top_heater_metal_.yml
  test-data-regression/test_netlists_mzi_pin_.yml
  test-data-regression/test_netlists_mzm_.yml
  test-data-regression/test_netlists_switch_tree_.yml
  test-data-regression/test_settings_bend_euler_s_.yml
  test-data-regression/test_settings_mzi1x2_2x2_.yml
  test-data-regression/test_settings_mzi2x2_2x2_.yml
  test-data-regression/test_settings_mzi2x2_2x2_phase_shifter_.yml
  test-data-regression/test_settings_mzi_.yml
  test-data-regression/test_settings_mzi_coupler_.yml
  test-data-regression/test_settings_mzi_phase_shifter_.yml
  test-data-regression/test_settings_mzi_phase_shifter_top_heater_metal_.yml
  test-data-regression/test_settings_mzi_pin_.yml
  test-data-regression/test_settings_mzm_.yml
Labels: maintenance

#3062 Fix rendering failure for 'i' and 'j' in font.py
  gdsfactory/font.py
Labels: bug

#3054 Add awg
  gdsfactory/components/__init__.py
  gdsfactory/components/awg.py
  test-data-regression/test_netlists_awg_.yml
  test-data-regression/test_settings_awg_.yml
Labels: maintenance

#3056 Remove cell decorator
  CHANGELOG.md
  gdsfactory/routing/add_electrical_pads_top.py
Labels: documentation

#3065 improve contribution guidelines
  docs/contribution.md
Labels: documentation

#3067 Add actionlint to pre-commit hooks
  .pre-commit-config.yaml
Labels: enhancement, github_actions
