Repository gdsfactory/gdsfactory, pull requests merged in 2024-08, with the labels that each got.

#3075 fix warning message
  gdsfactory/component.py
Labels: bug

#3076 pin max version of klayout
  pyproject.toml
Labels: dependencies

#3078 remove klayout pin
  .github/workflows/test_code.yml
  gdsfactory/components/text_freetype.py
  gdsfactory/cross_section.py
  gdsfactory/font.py
  gdsfactory/generic_tech/layer_map.py
  gdsfactory/generic_tech/layer_views.yaml
  gdsfactory/routing/route_single.py
  gdsfactory/routing/route_single_from_steps.py
  gdsfactory/technology/layer_map.py
  gdsfactory/technology/read_from_layers_info.py
  notebooks/03_layer_stack.ipynb
  pyproject.toml
  test-data-regression/test_netlists_text_freetype_.yml
  test-data-regression/test_settings_text_freetype_.yml
  tests/routing/test_route_single_from_steps.py
  tests/routing/test_routing_route_bundle.py
Labels: maintenance

#3085 fix route_single width
  gdsfactory/pdk.py
  gdsfactory/routing/route_single.py
  test-data-regression/test_netlists_coh_tx_dual_pol_.yml
  test-data-regression/test_netlists_coh_tx_single_pol_.yml
  test-data-regression/test_netlists_edge_coupler_array_with_loopback_.yml
  test-data-regression/test_netlists_loss_deembedding_ch12_34_.yml
  test-data-regression/test_netlists_loss_deembedding_ch13_24_.yml
  test-data-regression/test_netlists_loss_deembedding_ch14_23_.yml
  test-data-regression/test_netlists_spiral_racetrack_fixed_length_.yml
  test-data-regression/test_netlists_splitter_tree_.yml
  test-data-regression/test_netlists_straight_heater_meander_doped_.yml
  test-data-regression/test_netlists_switch_tree_.yml
Labels: bug

#3087 faster Component.extract()
  gdsfactory/component.py
Labels: maintenance

#3090 fix bend coupler output cross section
  gdsfactory/components/ring_single_bend_coupler.py
  tests/components/test_components.py
Labels: bug

#3080 fix difftest
  gdsfactory/difftest.py
  tests/test_diff.py
Labels: bug

#3094 fix add_ports
  gdsfactory/add_ports.py
  tests/components/test_netlists.py
Labels: bug

#3095 fix watcher examples
  gdsfactory/cli.py
  gdsfactory/samples/demo/circuits/pads.pic.yml
  gdsfactory/watch.py
Labels: bug

#3097 Watcher improve
  gdsfactory/cli.py
  gdsfactory/get_factories.py
  gdsfactory/samples/demo/pcell.py
  gdsfactory/watch.py
Labels: maintenance

#3099 better diffest names
  gdsfactory/difftest.py
Labels: maintenance

#3100 fix layer serialization
  gdsfactory/serialization.py
  tests/test_serialization.py
Labels: bug

#3101 improve docs generation
  .github/workflows/pages.yml
  .gitignore
  Makefile
  docs/components.rst
Labels: bug, documentation

#3103 add_fiber_array works with fiber port
  gdsfactory/components/via_corner.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/samples/demo/circuits/mask.pic.yml
Labels: bug

#3104 improve yaml
  gdsfactory/components/pack_doe.py
  gdsfactory/pdk.py
  gdsfactory/read/from_yaml.py
  gdsfactory/samples/demo/circuits/mask.pic.yml
  gdsfactory/schematic.py
Labels: bug

#3105 Add containers
  Makefile
  docs/write_cells.py
  gdsfactory/__init__.py
  gdsfactory/add_loopback.py
  gdsfactory/components/__init__.py
  gdsfactory/containers.py
  gdsfactory/pdk.py
Labels: enhancement

#3107 avoid warnings for unnamed references
  gdsfactory/component.py
  gdsfactory/components/rectangle.py
  gdsfactory/components/seal_ring.py
Labels: bug

#3113 fix wire corner ports
  gdsfactory/components/wire.py
  notebooks/03_Path_CrossSection.ipynb
  notebooks/08_pdk.ipynb
  test-data-regression/test_netlists_wire_corner_.yml
  test-data-regression/test_route_bundle_obstacle.yml
  test-data-regression/test_route_bundle_udirect_pads.yml
  test-data-regression/test_route_bundle_west_to_north.yml
  test-data-regression/test_route_bundle_west_to_north2.yml
  tests/read/test_component_from_yaml.py
Labels: bug

#3114 watcher: possibly prerun all cells
  gdsfactory/cli.py
  gdsfactory/watch.py
Labels: maintenance

#3115 allow serialization as strings
  gdsfactory/serialization.py
Labels: maintenance

#3117 update numpy
  gdsfactory/labels/get_test_manifest.py
  gdsfactory/path.py
  pyproject.toml
Labels: maintenance, dependencies, github_actions

#3121 Expose port orientations
  gdsfactory/components/compass.py
  gdsfactory/components/pad.py
  gdsfactory/components/rectangle.py
  gdsfactory/components/via_stack.py
  test-data-regression/test_netlists_array_.yml
  test-data-regression/test_netlists_die_with_pads_.yml
  test-data-regression/test_netlists_disk_heater_.yml
  test-data-regression/test_netlists_ge_detector_straight_si_contacts_.yml
  test-data-regression/test_netlists_greek_cross_.yml
  test-data-regression/test_netlists_greek_cross_with_pads_.yml
  test-data-regression/test_netlists_pad_.yml
  test-data-regression/test_netlists_pad_array0_.yml
  test-data-regression/test_netlists_pad_array180_.yml
  test-data-regression/test_netlists_pad_array270_.yml
  test-data-regression/test_netlists_pad_array90_.yml
  test-data-regression/test_netlists_pad_array_.yml
  test-data-regression/test_netlists_pad_rectangular_.yml
  test-data-regression/test_netlists_pad_small_.yml
  test-data-regression/test_netlists_pads_shorted_.yml
  test-data-regression/test_netlists_resistance_sheet_.yml
  test-data-regression/test_netlists_ring_double_heater_.yml
  test-data-regression/test_netlists_ring_single_heater_.yml
  test-data-regression/test_netlists_seal_ring_.yml
  test-data-regression/test_netlists_seal_ring_segmented_.yml
  test-data-regression/test_netlists_spiral_racetrack_heater_metal_.yml
  test-data-regression/test_netlists_straight_heater_meander_doped_.yml
  test-data-regression/test_netlists_straight_heater_metal_.yml
  test-data-regression/test_netlists_straight_heater_metal_90_90_.yml
  test-data-regression/test_netlists_straight_heater_metal_simple_.yml
  test-data-regression/test_netlists_straight_heater_metal_undercut_.yml
  test-data-regression/test_netlists_straight_heater_metal_undercut_90_90_.yml
  test-data-regression/test_netlists_straight_pin_.yml
  test-data-regression/test_netlists_straight_pin_slot_.yml
  test-data-regression/test_netlists_straight_pn_.yml
  test-data-regression/test_netlists_via_chain_.yml
  test-data-regression/test_netlists_via_stack_.yml
  test-data-regression/test_netlists_via_stack_corner45_extended_.yml
  test-data-regression/test_netlists_via_stack_heater_m3_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_mini_.yml
  test-data-regression/test_netlists_via_stack_m1_mtop_.yml
  test-data-regression/test_netlists_via_stack_npp_m1_.yml
  test-data-regression/test_netlists_via_stack_slab_m1_horizontal_.yml
  test-data-regression/test_netlists_via_stack_slab_m3_.yml
  test-data-regression/test_netlists_via_stack_slab_npp_m3_.yml
  test-data-regression/test_settings_pad_.yml
  test-data-regression/test_settings_pad_rectangular_.yml
  test-data-regression/test_settings_pad_small_.yml
  test-data-regression/test_settings_via_stack_.yml
  test-data-regression/test_settings_via_stack_heater_m3_.yml
  test-data-regression/test_settings_via_stack_heater_mtop_.yml
  test-data-regression/test_settings_via_stack_heater_mtop_mini_.yml
  test-data-regression/test_settings_via_stack_m1_mtop_.yml
  test-data-regression/test_settings_via_stack_npp_m1_.yml
  test-data-regression/test_settings_via_stack_slab_m1_horizontal_.yml
  test-data-regression/test_settings_via_stack_slab_m3_.yml
  test-data-regression/test_settings_via_stack_slab_npp_m3_.yml
Labels: maintenance

#3124 fix bend_circular bbox
  gdsfactory/components/bend_circular.py
Labels: bug

#3126 fix die layer
  gdsfactory/components/die.py
  gdsfactory/components/die_with_pads.py
  gdsfactory/typings.py
  test-data-regression/test_netlists_die_.yml
Labels: bug

#3125 update to docker to python3.12
  .devcontainer/Dockerfile.dev
  .devcontainer/Dockerfile.dev_minimal
  .devcontainer/Dockerfile.web
  .devcontainer/Makefile
  .devcontainer/run.sh
  pyproject.toml
Labels: dependencies, github_actions

#3128 Fix minimum length of path for gradient
  gdsfactory/path.py
Labels: bug

#3131 text rectangular multilayer
  gdsfactory/components/text_rectangular.py
Labels: bug

#3132 fix tests
  gdsfactory/components/text_rectangular.py
  test-data-regression/test_netlists_text_rectangular_multi_layer_.yml
  test-data-regression/test_settings_text_rectangular_multi_layer_.yml
Labels: bug

#3133 fix type annotation for layer
  gdsfactory/typings.py
Labels: bug

#3136 make functions work with Kcells
  gdsfactory/boolean.py
  gdsfactory/component.py
  gdsfactory/functions.py
Labels: bug

#3137 lower warn level for layout read
  gdsfactory/read/import_gds.py
Labels: bug

#3139 More robust netlist extraction
  gdsfactory/components/straight_heater_meander_doped.py
  gdsfactory/get_netlist.py
  gdsfactory/read/import_gds.py
  test-data-regression/test_netlists_straight_heater_meander_doped_.yml
Labels: bug

#3145 fix pre-commit
  notebooks/03_Path_CrossSection.ipynb
  notebooks/03_layer_stack.ipynb
  notebooks/07_mask.ipynb
  notebooks/_0_python.ipynb
Labels: bug

#3151 enable_layout_cache
  gdsfactory/config.py
  tests/test_cell.py
Labels: enhancement

#3156 Update `list[LayerSpec]` types to `LayerSpecs`
  gdsfactory/component.py
  gdsfactory/functions.py
Labels: bug

#3153 annotate failures in github
  pyproject.toml
Labels: dependencies, github_actions

#3154 add cell decorator to import_gds
  gdsfactory/read/import_gds.py
  tests/read/test_import_gds.py
Labels: enhancement

#3158 Update kfactory0192
  pyproject.toml
Labels: dependencies

#3159 decorate import_gds with cache
  gdsfactory/read/import_gds.py
Labels: maintenance

#3162 Match `post_process` in `import_gds` to `@gf.cell`
  gdsfactory/read/import_gds.py
  tests/test_add_ports.py
Labels: feature

#3165 improve text rectangular
  Makefile
  gdsfactory/components/text_rectangular.py
  pyproject.toml
  test-data-regression/test_netlists_cdsem_coupler_.yml
  test-data-regression/test_netlists_cdsem_straight_.yml
  test-data-regression/test_netlists_cdsem_straight_density_.yml
  test-data-regression/test_netlists_edge_coupler_array_.yml
  test-data-regression/test_netlists_text_lines_.yml
  test-data-regression/test_netlists_text_rectangular_.yml
  test-data-regression/test_netlists_text_rectangular_mini_.yml
  test-data-regression/test_netlists_text_rectangular_multi_layer_.yml
  test-data-regression/test_settings_text_rectangular_.yml
  test-data-regression/test_settings_text_rectangular_mini_.yml
Labels: bug
