Repository gdsfactory/gdsfactory, pull requests merged in 2024-06, with the labels that each got.

#2809 add ports from boxes
  gdsfactory/add_ports.py
  gdsfactory/component.py
  tests/test_add_ports.py
Labels: enhancement

#2811 fix less than 1nm issue
  gdsfactory/add_ports.py
  gdsfactory/port.py
Labels: bug

#2812 taper=None by default
  gdsfactory/routing/route_single.py
Labels: bug

#2813 serialize layer by name
  gdsfactory/serialization.py
Labels: bug

#2814 Fix mmis
  CHANGELOG.md
  gdsfactory/components/mmi.py
  gdsfactory/components/mmi1x2.py
  gdsfactory/components/mmi2x2.py
  gdsfactory/samples/pdk/fab_c.py
  notebooks/08_pdk.ipynb
Labels: bug, documentation

#2815 Fix grating coupler rectangular
  CHANGELOG.md
  gdsfactory/cli.py
  gdsfactory/components/grating_coupler_array.py
  gdsfactory/components/grating_coupler_rectangular.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary_slab.py
  gdsfactory/config.py
  gdsfactory/export/to_gerber.py
  gdsfactory/samples/pdk/fab_d/phase_shifters.py
  pyproject.toml
  test-data-regression/test_settings_grating_coupler_rectangular_.yml
  test-data-regression/test_settings_grating_coupler_rectangular_arbitrary_slab_.yml
Labels: bug, documentation

#2817 minor fixes
  gdsfactory/add_ports.py
  gdsfactory/component.py
  gdsfactory/component_layout.py
  gdsfactory/components/__init__.py
  gdsfactory/components/compass.py
  gdsfactory/components/component_sequence.py
  gdsfactory/components/ring_crow.py
  gdsfactory/components/spiral_heater.py
  gdsfactory/components/splitter_tree.py
  gdsfactory/components/straight.py
  gdsfactory/components/straight_heater_meander.py
  gdsfactory/generic_tech/klayout/lvs/testing/testcases/unit/heater_devices/layout/straight_heater_metal.py
  gdsfactory/port.py
  gdsfactory/read/from_yaml.py
  gdsfactory/routing/add_electrical_pads_top_dc.py
  gdsfactory/typings.py
  gdsfactory/write_cells.py
  notebooks/04_routing_electrical.ipynb
  notebooks/10_yaml_component.ipynb
  notebooks/yaml_pics/aar_around_the_back.pic.yml
  notebooks/yaml_pics/aar_around_the_back2.pic.yml
  notebooks/yaml_pics/aar_around_the_back3.pic.yml
  notebooks/yaml_pics/aar_bundles01.pic.yml
  notebooks/yaml_pics/aar_bundles02.pic.yml
  notebooks/yaml_pics/aar_bundles03.pic.yml
  notebooks/yaml_pics/aar_indirect.pic.yml
  notebooks/yaml_pics/aar_simple.pic.yml
  notebooks/yaml_pics/aar_steps01.pic.yml
  notebooks/yaml_pics/aar_steps02_final.pic.yml
  notebooks/yaml_pics/aar_steps02_initial.pic.yml
  notebooks/yaml_pics/aar_steps03.pic.yml
  notebooks/yaml_pics/aar_wonky_connector.pic.yml
  notebooks/yaml_pics/routes_path_length_match.pic.yml
  test-data-regression/test_settings_add_fiber_single_.yml
  test-data-regression/test_settings_ring_crow_.yml
  test-data-regression/test_settings_sample_different_link_factory_.yml
  test-data-regression/test_settings_sample_waypoints_.yml
  test-data-regression/test_settings_spiral_racetrack_heater_metal_.yml
  test-data-regression/test_settings_via_chain_.yml
Labels: bug

#2820 uncomment skip tests
  docs/api.rst
  gdsfactory/component.py
  gdsfactory/components/__init__.py
  gdsfactory/components/bend_s.py
  gdsfactory/components/coupler_full.py
  gdsfactory/components/dbr_tapered.py
  gdsfactory/components/grating_coupler_dual_pol.py
  gdsfactory/components/grating_coupler_loss.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary_slab.py
  gdsfactory/components/greek_cross.py
  gdsfactory/components/loop_mirror.py
  gdsfactory/components/mmi1x2.py
  gdsfactory/components/mmi2x2.py
  gdsfactory/components/mzi.py
  gdsfactory/components/mzi_lattice.py
  gdsfactory/components/polarization_splitter_rotator.py
  gdsfactory/components/resistance_sheet.py
  gdsfactory/components/spiral.py
  gdsfactory/components/spiral_heater.py
  gdsfactory/components/straight_heater_meander.py
  gdsfactory/components/straight_heater_metal.py
  gdsfactory/components/taper.py
  gdsfactory/components/taper_cross_section.py
  gdsfactory/components/via_stack.py
  gdsfactory/cross_section.py
  gdsfactory/get_netlist.py
  gdsfactory/get_netlist_flat.py
  gdsfactory/pdk.py
  gdsfactory/routing/route_single.py
  test-data-regression/test_settings_grating_coupler_rectangular_arbitrary_.yml
  test-data-regression/test_settings_greek_cross_.yml
  test-data-regression/test_settings_greek_cross_with_pads_.yml
  test-data-regression/test_settings_resistance_sheet_.yml
  test-data-regression/test_settings_ring_double_pn_.yml
  test-data-regression/test_settings_taper_cross_section_.yml
  test-data-regression/test_settings_taper_cross_section_linear_.yml
  test-data-regression/test_settings_taper_cross_section_parabolic_.yml
  test-data-regression/test_settings_taper_cross_section_sine_.yml
  test-data-regression/test_settings_via_stack_m1_mtop_.yml
  test-data-regression/test_settings_via_stack_npp_m1_.yml
  tests/components/test_netlists.py
  tests/routing/test_routing_route_bundle.py
  tests/test_get_netlist.py
  tests/test_get_netlist_recursive.py
  tests/test_netlists.py
  tests/test_netlists_flat.py
Labels: bug

#2824 remove unused packages
  .gitignore
  pyproject.toml
Labels: dependencies

#2825 improve docs
  docs/developer.md
Labels: documentation

#2827 update kfactory pin
  gdsfactory/component.py
  pyproject.toml
Labels: dependencies

#2828 Add die with pads
  docs/components.rst
  gdsfactory/components/__init__.py
  gdsfactory/components/die_with_pads.py
  test-data-regression/test_settings_die_with_pads_.yml
Labels: enhancement

#2835 fix ring_double
  gdsfactory/components/ring_double.py
  notebooks/12_grid_snapping.ipynb
  notebooks/21_migration_guide_7_8.ipynb
Labels: bug

#2836 improve docs
  README.md
  docs/_toc.yml
  docs/developer.md
  gdsfactory/component.py
  gdsfactory/samples/01_component_pcell.py
  gdsfactory/samples/03_move.py
  gdsfactory/samples/05_remove_layers.py
  gdsfactory/samples/06_remapping_layers.py
  gdsfactory/samples/07_flattening_device.py
  gdsfactory/samples/08_grid.py
  gdsfactory/samples/08_group.py
  gdsfactory/samples/09_pack.py
  gdsfactory/samples/12_component_refs.py
  gdsfactory/samples/14_component_connectivity.py
  gdsfactory/samples/17_ports.py
  gdsfactory/samples/22_add_pads.py
  gdsfactory/samples/24_doe.py
  gdsfactory/samples/24_doe_2.py
  gdsfactory/samples/24_doe_3.py
  gdsfactory/samples/30_lidar.py
  gdsfactory/samples/30_lidar_pcell.py
  gdsfactory/samples/30_lidar_with_pads.py
  gdsfactory/samples/30_route_bundle_lidar.py
  gdsfactory/samples/31_route_bundle_impossible.py
  gdsfactory/samples/33_route_bundle_nxn.py
  gdsfactory/samples/big_device.py
  notebooks/03_cells_autoname_and_cache.ipynb
  notebooks/04_components_pack.ipynb
  notebooks/04_routing.ipynb
  notebooks/08_pdk.ipynb
  notebooks/12_grid_snapping.ipynb
  notebooks/_2_klayout.ipynb
  notebooks/_4_gdsfactory.ipynb
Labels: documentation

#2838 make cli to be consistent using dashes
  gdsfactory/cli.py
  gdsfactory/samples/demo/lvs.py
Labels: documentation

#2839 improve docs
  docs/_toc.yml
  notebooks/_0_python.ipynb
  notebooks/_2_klayout.ipynb
  notebooks/_3_vscode.ipynb
  notebooks/_4_gdsfactory.ipynb
Labels: documentation

#2840 remove gf.asserts and picmodel
  gdsfactory/__init__.py
  gdsfactory/asserts.py
  gdsfactory/components/grating_coupler_dual_pol.py
  gdsfactory/components/grating_coupler_rectangular.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary.py
  gdsfactory/picmodel.py
  gdsfactory/symbols.py
  pyproject.toml
Labels: maintenance

#2805 Proposal: simpler LayerStack and DerivedLayers
  docs/_toc.yml
  gdsfactory/component.py
  gdsfactory/config.py
  gdsfactory/export/to_3d.py
  gdsfactory/export/to_stl.py
  gdsfactory/generic_tech/layer_stack.py
  gdsfactory/samples/pdk/fab_c.py
  gdsfactory/technology/__init__.py
  gdsfactory/technology/layer_stack.py
  gdsfactory/technology/processes.py
  notebooks/03_layer_stack.ipynb
  notebooks/08_pdk_examples.ipynb
  pyproject.toml
  tests/export/test_export_to_3d.py
  tests/export/test_export_to_stl.py
  tests/technology/test_layerstack.py
Labels: enhancement, minor

#2845 Improve geometry docs
  gdsfactory/samples/netlists/bend_rotated.yml
  notebooks/04_components_geometry.ipynb
  tests/test_get_netlist_yaml3.py
Labels: documentation

#2849 Avoid duplicated ports
  Makefile
  gdsfactory/components/pad.py
  gdsfactory/components/pad_gsg.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/routing/route_quad.py
  gdsfactory/samples/fixme/route_bundle_bbox.py
  notebooks/03_cells_autoname_and_cache.ipynb
  notebooks/_0_python.ipynb
  pyproject.toml
  test-data-regression/test_settings_add_pads0_.yml
  test-data-regression/test_settings_type1_.yml
  test-data-regression/test_settings_type2_.yml
  tests/routing/test_add_fiber_array.py
  tests/routing/test_add_pads.py
  tests/routing/test_routing_route_bundle.py
Labels: bug

#2854 add klayout_tech to pdk
  gdsfactory/pdk.py
  tests/routing/test_routing_route_bundle.py
Labels: enhancement

#2851 add klive dependency
  gdsfactory/generic_tech/klayout/grain.xml
Labels: enhancement

#2852 update kfactory
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/routing/route_single.py
  gdsfactory/samples/fixme/route_bundle_bbox2.py
  notebooks/04_routing.ipynb
  notebooks/04_routing_electrical.ipynb
  pyproject.toml
  test-data-regression/test_connect_bundle_udirect.yml
  test-data-regression/test_route_bundle_obstacle.yml
  tests/routing/test_add_pads.py
Labels: dependencies

#2868 Fix add pins triangle
  gdsfactory/add_pins.py
  gdsfactory/component.py
  gdsfactory/port.py
  tests/test_add_pins.py
Labels: bug

#2876 fix #2869 by adding a 'by' argument to get_polygons and get_polygons_points
  gdsfactory/component.py
  gdsfactory/export/to_np.py
Labels: bug

#2877 make 7to8 migration script more safe by default
  gdsfactory/cli.py
Labels: enhancement

#2878 Fix tests
  gdsfactory/export/to_3d.py
  gdsfactory/technology/layer_stack.py
  tests/test_component.py
Labels: bug

#2880 add seal_ring_segmented
  gdsfactory/__init__.py
  gdsfactory/component.py
  gdsfactory/components/__init__.py
  gdsfactory/components/seal_ring.py
  gdsfactory/components/via_stack.py
  gdsfactory/components/wire.py
  test-data-regression/test_netlists_seal_ring_segmented_.yml
  test-data-regression/test_netlists_via_stack_corner45_.yml
  test-data-regression/test_netlists_via_stack_corner45_extended_.yml
Labels: enhancement

#2889 fix get_layer
  gdsfactory/pdk.py
Labels: bug

#2890 pin version of kfactory with ==
  gdsfactory/add_ports.py
  gdsfactory/component.py
  gdsfactory/components/bend_s.py
  gdsfactory/pdk.py
  pyproject.toml
  test-data-regression/test_netlists_wire_corner45_.yml
  test-data-regression/test_settings_seal_ring_segmented_.yml
  test-data-regression/test_settings_via_stack_corner45_.yml
  test-data-regression/test_settings_via_stack_corner45_extended_.yml
  test-data-regression/test_settings_wire_corner45_.yml
Labels: bug

#2892 don't activate generic pdk
  gdsfactory/component.py
  gdsfactory/components/coupler.py
  gdsfactory/components/taper.py
  gdsfactory/config.py
  gdsfactory/pdk.py
  test-data-regression/test_netlists_coupler_.yml
  test-data-regression/test_netlists_mzit_.yml
  test-data-regression/test_netlists_ring_crow_couplers_.yml
  test-data-regression/test_settings_coupler_.yml
  tests/test_get_netlist.py
Labels: maintenance

#2893 Improve docs and from_updk
  gdsfactory/read/from_updk.py
  notebooks/00_geometry.ipynb
  pyproject.toml
Labels: maintenance

#2895 Remove gdstk dependency
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/write_cells.py
  pyproject.toml
Labels: bug, maintenance

#2894 improve route_fiber_array
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/route_fiber_array.py
Labels: bug, routing

#2900 fix plot_netlist
  gdsfactory/component.py
  gdsfactory/get_netlist.py
Labels: bug

#2901 fix route_bundle
  gdsfactory/routing/route_bundle.py
Labels: bug

#2904 Fix dicing_lane
  CHANGELOG.md
  docs/_toc.yml
  gdsfactory/component.py
  gdsfactory/components/dicing_lane.py
  gdsfactory/components/extension.py
  gdsfactory/components/grating_coupler_rectangular.py
  gdsfactory/components/ring_double.py
  gdsfactory/grid.py
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/typings.py
  gdsfactory/write_cells.py
  notebooks/12_config.ipynb
  pyproject.toml
  test-data-regression/test_netlists_dicing_lane_.yml
  test-data-regression/test_netlists_edge_coupler_array_with_loopback_.yml
  test-data-regression/test_netlists_extend_ports_.yml
  test-data-regression/test_netlists_straight_heater_meander_doped_.yml
  test-data-regression/test_settings_dicing_lane_.yml
  test-data-regression/test_settings_extend_ports_.yml
  tests/routing/test_add_pads.py
  tests/test_write_cells.py
Labels: bug, documentation, maintenance

#2908 fix changelog
  CHANGELOG.md
Labels: minor

#2909 save_options should be None by default
  gdsfactory/component.py
Labels: bug

#2914 Improve routing
  gdsfactory/component.py
  gdsfactory/components/seal_ring.py
  gdsfactory/components/via_stack.py
  gdsfactory/components/via_stack_with_offset.py
  gdsfactory/generic_tech/klayout/drc/errors.py
  gdsfactory/path.py
  gdsfactory/read/from_updk.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_quad.py
  gdsfactory/routing/route_sharp.py
  gdsfactory/routing/route_single.py
  gdsfactory/routing/route_single_from_steps.py
  gdsfactory/routing/route_single_sbend.py
  gdsfactory/routing/route_south.py
  gdsfactory/samples/demo/benchmark/fill_demo.py
  gdsfactory/samples/demo/benchmark/snap_demo_phidl.py
  gdsfactory/samples/demo/drc_errors.py
  gdsfactory/typings.py
  notebooks/01_references.ipynb
  notebooks/03_Path_CrossSection.ipynb
  notebooks/03_cells_autoname_and_cache.ipynb
  notebooks/04_routing.ipynb
  notebooks/04_routing_electrical.ipynb
  notebooks/10_yaml_component.ipynb
  notebooks/12_config.ipynb
  notebooks/yaml_pics/pads.pic.yml
  notebooks/yaml_pics/routes_custom.pic.yml
  test-data-regression/test_route_bundle_udirect_pads.yml
  test-data-regression/test_route_connect_bundle_udirect.yml
  tests/routing/test_routing_route_bundle_udirect.py
  tests/routing/test_routing_route_bundle_uindirect.py
Labels: routing, maintenance

#2916 fixes add_ports_from_labels
  gdsfactory/add_ports.py
Labels: bug

#2917 fix add_ports_from_labels
  gdsfactory/add_ports.py
  tests/test_add_ports.py
Labels: bug

#2920 add allow_layer_mismatch and allow_width_mismatch
  gdsfactory/routing/route_single_sbend.py
Labels: routing, maintenance

#2921 Update kfactory
  CHANGELOG.md
  gdsfactory/components/mmi2x2_with_sbend.py
  gdsfactory/components/mzi.py
  gdsfactory/components/mzi_arm.py
  gdsfactory/components/mzi_arms.py
  gdsfactory/components/ring_single_bend_coupler.py
  gdsfactory/components/spiral.py
  gdsfactory/components/spiral_double.py
  gdsfactory/difftest.py
  gdsfactory/samples/netlists/mzi.yml
  notebooks/04_routing_electrical.ipynb
  pyproject.toml
  test-data-regression/test_netlists_coh_tx_dual_pol_.yml
  test-data-regression/test_netlists_coh_tx_single_pol_.yml
  test-data-regression/test_netlists_coupler_ring_.yml
  test-data-regression/test_netlists_delay_snake_sbend_.yml
  test-data-regression/test_netlists_loss_deembedding_ch13_24_.yml
  test-data-regression/test_netlists_mzi2x2_2x2_.yml
  test-data-regression/test_netlists_mzi2x2_2x2_phase_shifter_.yml
  test-data-regression/test_netlists_mzi_arm_.yml
  test-data-regression/test_netlists_mzi_phase_shifter_.yml
  test-data-regression/test_netlists_mzi_phase_shifter_top_heater_metal_.yml
  test-data-regression/test_netlists_mzi_pin_.yml
  test-data-regression/test_netlists_mzm_.yml
  test-data-regression/test_netlists_spiral_.yml
  test-data-regression/test_netlists_straight_heater_meander_doped_.yml
  test-data-regression/test_netlists_switch_tree_.yml
  tests/test_component.py
  tests/test_get_netlist_yaml.py
Labels: documentation

#2918 Added spiral inductor in gdsfactory.components
  gdsfactory/components/__init__.py
  gdsfactory/components/spiral_inductor.py
  test-data-regression/test_netlists_spiral_inductor_.yml
  test-data-regression/test_settings_spiral_inductor_.yml
Labels: enhancement

#2923 better difftest to show old and new in separate dy
  gdsfactory/difftest.py
Labels: enhancement

#2924 add labels with old, new, xor
  CHANGELOG.md
  gdsfactory/difftest.py
Labels: documentation, enhancement
