Repository gdsfactory/gdsfactory, pull requests merged in 2024-11, with the labels that each got.

#3339 deprecate import_gds_with_conflicts and add pdk.version
  gdsfactory/generic_tech/__init__.py
  gdsfactory/generic_tech/klayout/tech.lyt
  gdsfactory/pdk.py
  gdsfactory/read/import_gds.py
Labels: enhancement

#3340 add test for test_write_test_manifest
  gdsfactory/labels/write_test_manifest.py
  gdsfactory/samples/sample_reticle.py
  gdsfactory/samples/sample_reticle_with_labels.py
  tests/labels/write_test_manifest.py
Labels: enhancement

#3333 Updated schematic library to graphviz
  .gitignore
  gdsfactory/component.py
  gdsfactory/components/mzi.py
  gdsfactory/get_netlist.py
  gdsfactory/schematic.py
  notebooks/10_schematic.ipynb
  pyproject.toml
  test-data-regression/test_netlists_mzi1x2_2x2_.yml
  test-data-regression/test_netlists_mzi2x2_2x2_.yml
  test-data-regression/test_netlists_mzi2x2_2x2_phase_shifter_.yml
  test-data-regression/test_netlists_mzi_.yml
  test-data-regression/test_netlists_mzi_coupler_.yml
  test-data-regression/test_netlists_mzi_phase_shifter_.yml
  test-data-regression/test_netlists_mzi_phase_shifter_top_heater_metal_.yml
  test-data-regression/test_netlists_mzi_pin_.yml
  test-data-regression/test_netlists_mzm_.yml
Labels: enhancement

#3344 Add sample reticle electrical
  gdsfactory/generic_tech/klayout/layers.lyp
  gdsfactory/generic_tech/layer_views.yaml
  gdsfactory/labels/write_test_manifest.py
  gdsfactory/samples/sample_reticle.py
  gdsfactory/samples/sample_reticle_electrical_with_labels.py
Labels: enhancement

#3348 install graphviz
  .github/workflows/pages.yml
  Makefile
Labels: bug

#3349 fix crow by removing hardcoded ring name
  gdsfactory/components/ring_crow.py
  test-data-regression/test_netlists_ring_crow_.yml
Labels: bug

#3341 get all cells in manifest
  gdsfactory/labels/write_test_manifest.py
Labels: bug

#3354 fix graphviz docs
  gdsfactory/component.py
  gdsfactory/schematic.py
  notebooks/10_schematic.ipynb
Labels: bug

#3355 Fix add fiber array excluded ports
  gdsfactory/components/grating_coupler_elliptical.py
  gdsfactory/routing/route_fiber_array.py
  test-data-regression/test_settings_sample_excluded_ports_.yml
  tests/routing/test_add_fiber_array.py
Labels: bug

#3357 Pin python max version
  pyproject.toml
Labels: dependencies

#3356 add tests for python3.13
  .github/workflows/test_code.yml
  pyproject.toml
Labels: enhancement

#3358 add code example in readme
  README.md
Labels: documentation

#3361 Fix test manifest
  gdsfactory/components/greek_cross.py
  gdsfactory/labels/write_test_manifest.py
  test-data-regression/test_netlists_greek_cross_with_pads_.yml
  test-data-regression/test_settings_greek_cross_with_pads_.yml
Labels: bug

#3365 Fix route_bundle to allow routing electrical ports like optical ones #3363
  gdsfactory/routing/route_bundle.py
Labels: bug

#3366 fix missing start/end angles arg in route_bundle
  gdsfactory/routing/route_bundle.py
Labels: bug

#3367 Document route dubin
  gdsfactory/routing/route_dubin.py
  notebooks/04_routing.ipynb
  tests/routing/test_route_dubin.py
Labels: documentation

#3370 improve_text_klayout
  gdsfactory/components/text.py
  gdsfactory/components/text_freetype.py
  test-data-regression/test_import_json_label.yml
  test-data-regression/test_netlists_awg_.yml
  test-data-regression/test_netlists_coh_rx_single_pol_.yml
  test-data-regression/test_netlists_text_klayout_.yml
  test-data-regression/test_settings_text_klayout_.yml
Labels: maintenance

#3374 fix bend width
  gdsfactory/components/bend_circular.py
  gdsfactory/components/bend_euler.py
  test-data-regression/test_import_json_label.yml
  test-data-regression/test_netlists_awg_.yml
  test-data-regression/test_netlists_coh_rx_single_pol_.yml
  test-data-regression/test_netlists_mzit_.yml
Labels: bug

#3371 better pcell values
  gdsfactory/components/add_fiber_array_optical_south_electrical_north.py
  gdsfactory/components/component_sequence.py
  gdsfactory/components/mzi_pads_center.py
Labels: maintenance

#3375 Cleaner to um conversion
  gdsfactory/components/spiral_heater.py
  gdsfactory/components/straight_heater_meander.py
  gdsfactory/components/straight_heater_meander_doped.py
  gdsfactory/components/straight_pin.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/routing/route_single.py
  gdsfactory/snap.py
Labels: maintenance

#3377 add deprecation for ref.parent
  gdsfactory/component.py
Labels: maintenance, v7->v8

#3380 better netlist names for na/nb/dax/day -> columns/rows/column_pitch/row_pitch
  docs/write_cells.py
  gdsfactory/get_netlist.py
  gdsfactory/read/from_yaml.py
  gdsfactory/schematic.py
  notebooks/10_yaml_component.ipynb
  test-data-regression/test_netlists_array_.yml
  test-data-regression/test_netlists_dbr_.yml
  test-data-regression/test_netlists_grating_coupler_dual_pol_.yml
  test-data-regression/test_netlists_pad_array0_.yml
  test-data-regression/test_netlists_pad_array180_.yml
  test-data-regression/test_netlists_pad_array270_.yml
  test-data-regression/test_netlists_pad_array90_.yml
  test-data-regression/test_netlists_pad_array_.yml
  test-data-regression/test_netlists_via_chain_.yml
  test-data-regression/test_netlists_via_stack_.yml
  test-data-regression/test_netlists_via_stack_heater_m3_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_.yml
  test-data-regression/test_netlists_via_stack_m1_mtop_.yml
  test-data-regression/test_netlists_via_stack_npp_m1_.yml
  test-data-regression/test_netlists_via_stack_slab_m1_horizontal_.yml
  test-data-regression/test_netlists_via_stack_slab_m3_.yml
  test-data-regression/test_netlists_via_stack_slab_npp_m3_.yml
  test-data-regression/test_netlists_via_stack_with_offset_.yml
  tests/components/test_netlists.py
  tests/read/test_component_from_yaml.py
  tests/test_get_netlist.py
Labels: enhancement

#3384 fix cutback_component
  gdsfactory/components/cutback_component.py
Labels: bug

#3385 fix array placement
  gdsfactory/read/from_yaml.py
  test-data-regression/test_gds_and_settings_sample_array_connect_.yml
  tests/read/test_component_from_yaml.py
Labels: bug

#3386 Fix port orientation
  gdsfactory/port.py
  tests/test_port.py
Labels: bug

#3390 fix layer or width for bends
  gdsfactory/components/bend_circular.py
  gdsfactory/components/bend_euler.py
Labels: bug

#3392 Fix return typing for get_boxes()
  gdsfactory/component.py
Labels: bug

#3397 add rotate
  .github/workflows/test_code.yml
  gdsfactory/containers.py
  gdsfactory/functions.py
Labels: enhancement, maintenance

#3399 Make ComponentAlongPath accessible
  gdsfactory/__init__.py
Labels: maintenance

#3400 bump kfactory
  pyproject.toml
Labels: dependencies

#3398 Re-type `LayerViews.layers`
  gdsfactory/technology/layer_views.py
Labels: maintenance

#3401 fix docs
  gdsfactory/routing/route_single.py
  gdsfactory/technology/layer_map.py
  gdsfactory/technology/layer_views.py
  notebooks/09_pdk_import.ipynb
  tests/technology/test_layer_views.py
Labels: bug, documentation

#3404 fixes PortWidthMismatch error when setting cross_section in MZI
  gdsfactory/components/mzi.py
Labels: bug

#3405 use uv for installing
  .github/workflows/pages.yml
  .github/workflows/test_code.yml
  .gitignore
  Makefile
  docs/developer.md
  pyproject.toml
  uv.lock
Labels: documentation, dependencies

#3406 Update kfactory02111
  docs/developer.md
  pyproject.toml
Labels: documentation, dependencies

#3407 expose version in gdsfactory.__init__
  gdsfactory/__init__.py
Labels: maintenance

#3409 Improve yaml mirror docs
  gdsfactory/components/array_component.py
  gdsfactory/components/pad.py
  gdsfactory/read/from_yaml.py
  notebooks/10_yaml_component.ipynb
  test-data-regression/test_netlists_array_.yml
  test-data-regression/test_netlists_dbr_tapered_.yml
  test-data-regression/test_netlists_mzi_pads_center_.yml
  test-data-regression/test_netlists_pad_array0_.yml
  test-data-regression/test_netlists_pad_array180_.yml
  test-data-regression/test_netlists_pad_array270_.yml
  test-data-regression/test_netlists_pad_array90_.yml
  test-data-regression/test_netlists_pad_array_.yml
  test-data-regression/test_netlists_pad_gsg_open_.yml
  test-data-regression/test_netlists_pad_gsg_short_.yml
  test-data-regression/test_netlists_rectangle_with_slits_.yml
  test-data-regression/test_netlists_seal_ring_segmented_.yml
  test-data-regression/test_settings_array_.yml
  test-data-regression/test_settings_pad_array0_.yml
  test-data-regression/test_settings_pad_array180_.yml
  test-data-regression/test_settings_pad_array270_.yml
  test-data-regression/test_settings_pad_array90_.yml
  test-data-regression/test_settings_pad_array_.yml
Labels: documentation

#3410 Deprecate array spacing
  gdsfactory/component.py
  gdsfactory/components/array_component.py
  gdsfactory/components/compass.py
  gdsfactory/components/pad.py
  gdsfactory/components/rectangle_with_slits.py
  gdsfactory/components/via_chain.py
  gdsfactory/components/via_stack.py
  gdsfactory/components/via_stack_with_offset.py
  gdsfactory/config.py
  gdsfactory/read/from_yaml.py
  gdsfactory/schematic.py
  notebooks/01_references.ipynb
  notebooks/11_best_practices.ipynb
  test-data-regression/test_netlists_array_.yml
  test-data-regression/test_netlists_dbr_tapered_.yml
  test-data-regression/test_netlists_die_with_pads_.yml
  test-data-regression/test_netlists_greek_cross_with_pads_.yml
  test-data-regression/test_netlists_mzi_pads_center_.yml
  test-data-regression/test_netlists_pad_.yml
  test-data-regression/test_netlists_pad_array0_.yml
  test-data-regression/test_netlists_pad_array180_.yml
  test-data-regression/test_netlists_pad_array270_.yml
  test-data-regression/test_netlists_pad_array90_.yml
  test-data-regression/test_netlists_pad_array_.yml
  test-data-regression/test_netlists_pad_gsg_open_.yml
  test-data-regression/test_netlists_pad_gsg_short_.yml
  test-data-regression/test_netlists_pad_rectangular_.yml
  test-data-regression/test_netlists_pad_small_.yml
  test-data-regression/test_netlists_pads_shorted_.yml
  test-data-regression/test_netlists_rectangle_with_slits_.yml
  test-data-regression/test_netlists_seal_ring_segmented_.yml
  test-data-regression/test_netlists_via_chain_.yml
  test-data-regression/test_settings_array_.yml
  test-data-regression/test_settings_pad_.yml
  test-data-regression/test_settings_pad_array0_.yml
  test-data-regression/test_settings_pad_array180_.yml
  test-data-regression/test_settings_pad_array270_.yml
  test-data-regression/test_settings_pad_array90_.yml
  test-data-regression/test_settings_pad_array_.yml
  test-data-regression/test_settings_pad_rectangular_.yml
  test-data-regression/test_settings_pad_small_.yml
  test-data-regression/test_settings_rectangle_with_slits_.yml
Labels: enhancement

#3412 better array default
  gdsfactory/schematic.py
Labels: bug

#3413 fix bundle cross_section
  gdsfactory/routing/route_bundle.py
  tests/routing/test_routing_route_bundle.py
Labels: bug

#3416 improve plot_graphviz
  gdsfactory/schematic.py
Labels: maintenance

#3419 remove Transition inheritance
  gdsfactory/cross_section.py
  gdsfactory/path.py
  gdsfactory/typings.py
  notebooks/03_Path_CrossSection.ipynb
Labels: enhancement

#3418 fix dbr issues
  gdsfactory/components/dbr.py
  gdsfactory/components/dbr_tapered.py
  test-data-regression/test_netlists_dbr_tapered_.yml
Labels: bug

#3420 fix: remove Transition from get_cross_section return type
  gdsfactory/path.py
  gdsfactory/pdk.py
  tests/test_paths_extrude.py
  uv.lock
Labels: maintenance

#3424 Remove deprecated spacing
  gdsfactory/components/add_fiber_array_optical_south_electrical_north.py
  gdsfactory/components/array_component.py
  notebooks/07_mask.ipynb
Labels: maintenance

#3429 fix cli
  gdsfactory/cli.py
Labels: bug

#3427 Improve via_stack ports
  gdsfactory/components/compass.py
  gdsfactory/components/dbr.py
  gdsfactory/components/via_stack.py
  gdsfactory/components/via_stack_with_offset.py
  test-data-regression/test_netlists_compass_.yml
  test-data-regression/test_netlists_dbr_cell_.yml
  test-data-regression/test_netlists_disk_heater_.yml
  test-data-regression/test_netlists_ge_detector_straight_si_contacts_.yml
  test-data-regression/test_netlists_greek_cross_with_pads_.yml
  test-data-regression/test_netlists_resistance_sheet_.yml
  test-data-regression/test_netlists_ring_double_heater_.yml
  test-data-regression/test_netlists_ring_single_heater_.yml
  test-data-regression/test_netlists_seal_ring_.yml
  test-data-regression/test_netlists_seal_ring_segmented_.yml
  test-data-regression/test_netlists_snspd_.yml
  test-data-regression/test_netlists_straight_pin_.yml
  test-data-regression/test_netlists_straight_pin_slot_.yml
  test-data-regression/test_netlists_straight_pn_.yml
  test-data-regression/test_netlists_via_chain_.yml
  test-data-regression/test_netlists_via_stack_.yml
  test-data-regression/test_netlists_via_stack_corner45_extended_.yml
  test-data-regression/test_netlists_via_stack_heater_m3_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_mini_.yml
  test-data-regression/test_netlists_via_stack_m1_mtop_.yml
  test-data-regression/test_netlists_via_stack_npp_m1_.yml
  test-data-regression/test_netlists_via_stack_slab_m1_horizontal_.yml
  test-data-regression/test_netlists_via_stack_slab_m3_.yml
  test-data-regression/test_netlists_via_stack_slab_npp_m3_.yml
  test-data-regression/test_netlists_via_stack_with_offset_.yml
  test-data-regression/test_settings_compass_.yml
  test-data-regression/test_settings_via_stack_.yml
  test-data-regression/test_settings_via_stack_heater_m3_.yml
  test-data-regression/test_settings_via_stack_heater_mtop_.yml
  test-data-regression/test_settings_via_stack_heater_mtop_mini_.yml
  test-data-regression/test_settings_via_stack_m1_mtop_.yml
  test-data-regression/test_settings_via_stack_npp_m1_.yml
  test-data-regression/test_settings_via_stack_slab_m1_horizontal_.yml
  test-data-regression/test_settings_via_stack_slab_m3_.yml
  test-data-regression/test_settings_via_stack_slab_npp_m3_.yml
  test-data-regression/test_settings_via_stack_with_offset_.yml
Labels: enhancement

#3430 clear import cache on clearing layout cache
  .pre-commit-config.yaml
  gdsfactory/__init__.py
  gdsfactory/components/crossing_waveguide.py
Labels: bug

#3431 fix ruff
  gdsfactory/export/to_gerber.py
  gdsfactory/export/to_svg.py
Labels: bug

#3437 Add missing docs
  gdsfactory/cross_section.py
Labels: documentation, enhancement

#3438 Add plot to updk
  gdsfactory/read/from_updk.py
  gdsfactory/serialization.py
Labels: maintenance

#3439 Fix remove layers
  gdsfactory/component.py
  tests/test_component.py
  tests/test_serialization.py
Labels: bug

#3443 fix grid docs
  gdsfactory/grid.py
  notebooks/04_components_pack.ipynb
Labels: bug
