Repository gdsfactory/gdsfactory, pull requests merged in 2024-03, with the labels that each got.

#2573 Improve pdk import
  .github/workflows/pages.yml
  README.md
  gdsfactory/add_ports.py
  gdsfactory/components/die.py
  gdsfactory/components/nxn.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/samples/demo/circuits/mzi_lattice_filter_pdk.pic.yml
  gdsfactory/samples/demo/circuits/pads.pic.yml
  gdsfactory/technology/layer_views.py
  gdsfactory/write_cells.py
  notebooks/04_routing.ipynb
  test-data-regression/test_get_bundle_optical.yml
  test-data-regression/test_get_bundle_optical2.yml
  test-data-regression/test_get_bundle_u_direct_different_x.yml
  test-data-regression/test_import_json_label.yml
  test-data-regression/test_link_optical_ports_no_grouping.yml
  test-data-regression/test_rename_ports_electrical_.yml
  test-data-regression/test_rename_ports_optical_.yml
  test-data-regression/test_rename_ports_placement_.yml
  test-data-regression/test_settings_add_fiber_single_.yml
  test-data-regression/test_settings_die_.yml
  test-data-regression/test_settings_nxn_.yml
  tests/test_component_from_yaml.py
Labels: documentation, enhancement

#2574 Improve docs
  docs/workflow.md
  gdsfactory/components/add_fiber_array_optical_south_electrical_north.py
  gdsfactory/grid.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/typings.py
  test-data-regression/test_import_json_label.yml
  test-data-regression/test_settings_add_fiber_single_.yml
Labels: documentation, maintenance

#2575 fix taper
  gdsfactory/components/grating_coupler_rectangular.py
  gdsfactory/components/taper.py
  test-data-regression/test_settings_grating_coupler_rectangular_.yml
Labels: bug, maintenance

#2577 fix bend_direction ports
  gdsfactory/components/bend_euler.py
Labels: bug, maintenance

#2578 Better grating coupler names
  gdsfactory/asserts.py
  gdsfactory/components/grating_coupler_array.py
  gdsfactory/components/grating_coupler_elliptical.py
  gdsfactory/components/grating_coupler_elliptical_arbitrary.py
  gdsfactory/components/grating_coupler_elliptical_trenches.py
  gdsfactory/components/grating_coupler_rectangular.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary_slab.py
  gdsfactory/labels/write_labels.py
  gdsfactory/routing/get_route_from_steps.py
  test-data-regression/test_import_json_label.yml
  test-data-regression/test_settings_grating_coupler_array_.yml
  test-data-regression/test_settings_grating_coupler_rectangular_.yml
  test-data-regression/test_settings_grating_coupler_rectangular_arbitrary_.yml
  test-data-regression/test_settings_grating_coupler_rectangular_arbitrary_slab_.yml
  tests/test_import_gds_cell.py
  tests/test_label_custom.py
Labels: enhancement

#2579 Fix transition port size and MMIs with slab
  gdsfactory/components/grating_coupler_rectangular.py
  gdsfactory/components/mmi.py
  gdsfactory/components/mmi1x2.py
  gdsfactory/components/mmi2x2.py
  gdsfactory/components/taper.py
  gdsfactory/components/taper_cross_section.py
  gdsfactory/path.py
  test-data-regression/test_settings_mmi_.yml
Labels: bug

#2583 prevent validating schematic subdictionary of info
  gdsfactory/component_layout.py
Labels: enhancement

#2584 improve vias
  gdsfactory/components/straight_pin_slot.py
  gdsfactory/components/via.py
  gdsfactory/components/via_chain.py
  test-data-regression/test_settings_via1_.yml
  test-data-regression/test_settings_via2_.yml
  test-data-regression/test_settings_via_.yml
  test-data-regression/test_settings_via_chain_.yml
  test-data-regression/test_settings_viac_.yml
Labels: maintenance

#2592 Propagate `warnings.warn` category to loguru output
  gdsfactory/config.py
Labels: enhancement

#2597 add required layers
  gdsfactory/technology/layer_map.py
Labels: enhancement, maintenance

#2596 Add more pics
  gdsfactory/samples/demo/circuits/mzi1.pic.yml
  gdsfactory/samples/demo/circuits/mzi2.pic.yml
  gdsfactory/samples/demo/circuits/mzi_lattice_filter_generic.pic.yml
  gdsfactory/samples/demo/circuits/mzi_lattice_filter_generic_no_gratings.pic.yml
  gdsfactory/samples/demo/circuits/mzi_ubcpdk.pic.yml
Labels: maintenance

#2598 Accept callable or list
  gdsfactory/component.py
  gdsfactory/components/add_fiber_array_optical_south_electrical_north.py
  gdsfactory/components/add_fiducials.py
  gdsfactory/components/bbox.py
  gdsfactory/components/bend_circular.py
  gdsfactory/components/bend_circular_heater.py
  gdsfactory/components/bend_euler.py
  gdsfactory/components/bend_s.py
  gdsfactory/components/bezier.py
  gdsfactory/components/compass.py
  gdsfactory/components/coupler.py
  gdsfactory/components/coupler_ring.py
  gdsfactory/components/cross.py
  gdsfactory/components/grating_coupler_dual_pol.py
  gdsfactory/components/grating_coupler_elliptical.py
  gdsfactory/components/grating_coupler_elliptical_arbitrary.py
  gdsfactory/components/grating_coupler_elliptical_trenches.py
  gdsfactory/components/grating_coupler_rectangular.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary_slab.py
  gdsfactory/components/mmi.py
  gdsfactory/components/mmi1x2.py
  gdsfactory/components/mmi1x2_with_sbend.py
  gdsfactory/components/mmi2x2.py
  gdsfactory/components/mmi2x2_with_sbend.py
  gdsfactory/components/mzi.py
  gdsfactory/components/pad.py
  gdsfactory/components/resistance_sheet.py
  gdsfactory/components/straight.py
  gdsfactory/components/straight_heater_meander.py
  gdsfactory/components/taper.py
  gdsfactory/components/taper_cross_section.py
  gdsfactory/components/taper_from_csv.py
  gdsfactory/components/taper_parabolic.py
  gdsfactory/components/text_rectangular.py
  gdsfactory/components/triangles.py
  gdsfactory/components/via_stack.py
  gdsfactory/components/wire.py
  gdsfactory/path.py
  gdsfactory/read/import_gds.py
  gdsfactory/routing/add_electrical_pads_top.py
  gdsfactory/routing/add_electrical_pads_top_dc.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/routing/add_pads.py
Labels: enhancement

#2599 make gdsfactory less verbose
  gdsfactory/generic_tech/layer_map.py
  gdsfactory/pdk.py
  gdsfactory/technology/layer_map.py
Labels: maintenance

#2602 add default hatch_pattern
  gdsfactory/technology/layer_views.py
Labels: enhancement

#2603 remove start_straight_length from cross_section
  gdsfactory/cross_section.py
  gdsfactory/routing/get_bundle.py
  gdsfactory/routing/get_bundle_from_steps.py
  gdsfactory/routing/get_route.py
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_gc_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mmi1x2_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mmi1x2_no_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mzi_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mzi_no_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_nc_.yml
  test-data-regression/test_netlists_mzit_.yml
  test-data-regression/test_netlists_ring_double_.yml
  test-data-regression/test_netlists_ring_single_.yml
  test-data-regression/test_netlists_sample_different_link_factory_.yml
  test-data-regression/test_netlists_sample_docstring_.yml
  test-data-regression/test_netlists_sample_mmis_.yml
  test-data-regression/test_netlists_sample_waypoints_.yml
  test-data-regression/test_settings_straight_rib_.yml
  test-data-regression/test_settings_straight_rib_tapered_.yml
  test-data-regression/test_settings_tapers_.yml
  tests/routing/test_routing_get_bundle_electrical.py
Labels: bug

#2608 support activating more than 2 pdks
  docs/_toc.yml
  gdsfactory/component.py
  gdsfactory/config.py
  gdsfactory/pdk.py
  notebooks/08_pdk_examples.ipynb
  notebooks/12_config.ipynb
Labels: enhancement

#2614 Add models to pdk
  gdsfactory/config.py
  gdsfactory/cross_section.py
  gdsfactory/pdk.py
  gdsfactory/routing/get_bundle.py
  gdsfactory/routing/get_bundle_corner.py
  gdsfactory/routing/get_bundle_u.py
  gdsfactory/routing/get_route.py
  gdsfactory/routing/manhattan.py
  gdsfactory/samples/demo/Makefile
  gdsfactory/samples/demo/benchmark/fill_demo.py
  gdsfactory/samples/demo/benchmark/snap_demo_phidl.py
  gdsfactory/typings.py
  notebooks/04_routing.ipynb
  tests/routing/test_routing_get_bundle.py
  tests/routing/test_routing_get_bundle_electrical.py
Labels: enhancement

#2615 Fix electrical corner port location
  gdsfactory/components/__init__.py
  gdsfactory/components/cavity.py
  gdsfactory/components/pad.py
  gdsfactory/components/wire.py
  gdsfactory/components/wire_sbend.py
  gdsfactory/generic_tech/layer_map.py
  gdsfactory/routing/add_electrical_pads_shortest.py
  gdsfactory/routing/add_electrical_pads_top.py
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/get_bundle.py
  gdsfactory/routing/get_route.py
  gdsfactory/routing/manhattan.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/routing/route_south.py
  test-data-regression/test_get_bundle_electrical.yml
  test-data-regression/test_get_bundle_electrical2.yml
  test-data-regression/test_get_bundle_west_to_north.yml
  test-data-regression/test_get_bundle_west_to_north2.yml
  test-data-regression/test_get_route.yml
  test-data-regression/test_settings_add_pads_bot_.yml
Labels: bug

#2616 deprecate gf.fill
  gdsfactory/fill.py
Labels: maintenance

#2617 fix read_from_yaml with x=instance,port
  gdsfactory/read/from_yaml.py
Labels: bug

#2631 fix ring_pn
  gdsfactory/components/ring_double_pn.py
Labels: bug

#2629 clean polygon vertices after converting to numpy array
  gdsfactory/serialization.py
Labels: bug

#2634 more processes
  gdsfactory/technology/processes.py
Labels: enhancement

#2622 Add schematic
  gdsfactory/components/__init__.py
  gdsfactory/components/bend_euler.py
  gdsfactory/components/straight.py
  gdsfactory/samples/50_schematic.py
  gdsfactory/typings.py
Labels: enhancement

#2638 add get_cross_section_name from pdk
  gdsfactory/cross_section.py
  gdsfactory/pdk.py
Labels: enhancement

#2639 cross_section can be defined as a dict derived from a cross_section
  gdsfactory/pdk.py
  tests/test_component_from_yaml.py
Labels: bug

#2640 Better schematic docs
  .gitignore
  docs/_toc.yml
  gdsfactory/components/array_component.py
  gdsfactory/cross_section.py
  gdsfactory/typings.py
  notebooks/10_schematic.ipynb
  test-data-regression/test_settings_array_.yml
  tests/test_serialize.py
  tests/test_typings.py
Labels: maintenance

#2641 Small improvements
  gdsfactory/components/grating_coupler_elliptical_trenches.py
  gdsfactory/components/mmi.py
  gdsfactory/components/mmi1x2.py
  gdsfactory/components/mmi2x2.py
  gdsfactory/components/straight.py
  gdsfactory/components/taper.py
  gdsfactory/samples/pdk/fab_c.py
  notebooks/10_schematic.ipynb
  test-data-regression/test_netlists_sample_connections_.yml
  test-data-regression/test_settings_tapers_.yml
Labels: bug

#2642 fix docs for straight_heater
  gdsfactory/components/straight_heater_meander.py
  gdsfactory/components/straight_heater_metal.py
  test-data-regression/test_settings_straight_heater_metal_.yml
  test-data-regression/test_settings_straight_heater_metal_90_90_.yml
  test-data-regression/test_settings_straight_heater_metal_simple_.yml
  test-data-regression/test_settings_straight_heater_metal_undercut_.yml
  test-data-regression/test_settings_straight_heater_metal_undercut_90_90_.yml
Labels: bug, maintenance

#2644 fix dc assymm
  gdsfactory/components/coupler_straight_asymmetric.py
Labels: bug

#2646 use partial instead of gf.partial
  gdsfactory/add_tapers_cross_section.py
  gdsfactory/functions.py
  gdsfactory/read/from_updk.py
  gdsfactory/serialization.py
  tests/test_change_keywords_in_nested_partials.py
Labels: maintenance

#2649 get_bundle_sbend for vertical ports
  gdsfactory/routing/get_bundle.py
  gdsfactory/routing/get_bundle_sbend.py
Labels: maintenance
