Repository gdsfactory/gdsfactory, pull requests merged in 2024-09, with the labels that each got.

#3169 Re-add missing a straight `ComponentSpec` to `route_from_single_steps`
  gdsfactory/routing/route_single_from_steps.py
Labels: bug, enhancement

#3166 update to kfactory 0.20.1
  docs/write_cells.py
  gdsfactory/boolean.py
  gdsfactory/components/straight_heater_doped.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_ports_to_side.py
  gdsfactory/routing/route_single.py
  gdsfactory/routing/route_single_from_steps.py
  gdsfactory/routing/route_south.py
  notebooks/04_routing_electrical.ipynb
  notebooks/demo_jinja.pic.yml
  notebooks/yaml_pics/pads.pic.yml
  notebooks/yaml_pics/routes_custom.pic.yml
  pyproject.toml
  tests/routing/test_routing_route_bundle_west_to_north.py
Labels: dependencies

#3174 fix snspd port_type
  gdsfactory/components/optimal_hairpin.py
  gdsfactory/components/snspd.py
  test-data-regression/test_netlists_snspd_.yml
  test-data-regression/test_settings_snspd_.yml
Labels: bug

#3175 fixes routing types
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_ports_to_side.py
  gdsfactory/routing/route_single.py
  gdsfactory/routing/route_single_from_steps.py
  gdsfactory/routing/route_south.py
Labels: bug

#3176 deprecate python3.10
  gdsfactory/config.py
  pyproject.toml
Labels: dependencies

#3177 enforce_python311_or_larger
  gdsfactory/config.py
  gdsfactory/generic_tech/klayout/lvs/drc_malformed/run_drc.py
  gdsfactory/generic_tech/klayout/lvs/run_lvs.py
  pyproject.toml
Labels: dependencies

#3178 remove docker_build_minimal
  .github/workflows/release.yml
Labels: dependencies

#3181 fixing hatch patterns in lyp generated from LayerViews
  gdsfactory/technology/layer_views.py
Labels: bug

#3183 add test for area
  tests/test_functions.py
Labels: enhancement

#3184 set watcher flags by default
  gdsfactory/cli.py
Labels: maintenance

#3186 Improve docstrings
  gdsfactory/cell.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/technology/layer_views.py
  gdsfactory/technology/xml_utils.py
  gdsfactory/technology/yaml_utils.py
  gdsfactory/watch.py
  pyproject.toml
Labels: documentation

#3187 update_kfactory0202
  gdsfactory/routing/route_bundle.py
  pyproject.toml
  tests/test_component.py
  tests/test_functions.py
Labels: dependencies

#3193 watcher allows to overwrite existing cells
  gdsfactory/cli.py
  notebooks/12_config.ipynb
Labels: bug

#3201 Improve klayout extension
  gdsfactory/generic_tech/klayout/grain.xml
  gdsfactory/generic_tech/klayout/icon_128x128.png
  gdsfactory/generic_tech/klayout/icon_64x64.png
Labels: dependencies

#3202 fix klayout package image
  gdsfactory/generic_tech/klayout/grain.xml
Labels: documentation

#3203 improve klayout exension doc
  .github/workflows/test_pdks.yml
  notebooks/_2_klayout.ipynb
Labels: documentation

#3204 change to python311
  .devcontainer/Dockerfile.dev
Labels: dependencies

#3205 fix add_port returning the port itself instead of the actual added port
  gdsfactory/component.py
Labels: bug, enhancement

#3211 improve types
  gdsfactory/grid.py
  gdsfactory/typings.py
Labels: documentation

#3212 Check coupler radius
  gdsfactory/components/coupler.py
  test-data-regression/test_netlists_cavity_.yml
  test-data-regression/test_netlists_coupler_.yml
  test-data-regression/test_netlists_mzi_coupler_.yml
  test-data-regression/test_netlists_mzit_.yml
  test-data-regression/test_netlists_ring_crow_couplers_.yml
  test-data-regression/test_settings_coupler_.yml
Labels: documentation

#3214 better defaults for greek cross
  gdsfactory/components/greek_cross.py
  test-data-regression/test_netlists_greek_cross_.yml
  test-data-regression/test_netlists_greek_cross_with_pads_.yml
  test-data-regression/test_settings_greek_cross_.yml
Labels: maintenance

#3219 More generic components
  gdsfactory/add_padding.py
  gdsfactory/components/verniers.py
  test-data-regression/test_netlists_verniers_.yml
  test-data-regression/test_settings_verniers_.yml
Labels: bug

#3226 fix docs
  gdsfactory/read/import_gds.py
  notebooks/09_pdk_import.ipynb
  notebooks/10_yaml_component.ipynb
  notebooks/yaml_pics/pads.pic.yml
Labels: documentation

#3229 update kfactory to 0.20.7
  pyproject.toml
Labels: dependencies

#3231 Add post process to array
  gdsfactory/components/array_component.py
  test-data-regression/test_netlists_array_.yml
  test-data-regression/test_netlists_dbr_tapered_.yml
  test-data-regression/test_netlists_mzi_pads_center_.yml
  test-data-regression/test_netlists_pad_gsg_open_.yml
  test-data-regression/test_netlists_pad_gsg_short_.yml
  test-data-regression/test_netlists_rectangle_with_slits_.yml
  test-data-regression/test_netlists_seal_ring_segmented_.yml
  test-data-regression/test_settings_array_.yml
Labels: enhancement

#3232 make port array post_process and iterable
  gdsfactory/components/array_component.py
Labels: maintenance
