Repository gdsfactory/gdsfactory, pull requests merged in 2024-05, with the labels that each got.

#2713 improve updk port layer
  gdsfactory/read/from_updk.py
Labels: maintenance

#2714 improve get_cross_sections
  gdsfactory/components/mzm.py
  gdsfactory/components/taper.py
  gdsfactory/cross_section.py
  test-data-regression/test_settings_taper_sc_nc_.yml
  test-data-regression/test_settings_taper_strip_to_ridge_.yml
  tests/test_cross_section.py
Labels: bug

#2715 improve straight_heater_metal
  gdsfactory/components/straight_heater_meander.py
  gdsfactory/components/straight_heater_metal.py
  notebooks/01_references.ipynb
  notebooks/03_layer_stack.ipynb
  test-data-regression/test_settings_add_electrical_pads_shortest_.yml
  test-data-regression/test_settings_add_electrical_pads_top_.yml
  test-data-regression/test_settings_add_fiber_single_.yml
  test-data-regression/test_settings_add_padding_container_.yml
  test-data-regression/test_settings_add_pads_bot_.yml
  test-data-regression/test_settings_add_pads_top_.yml
  test-data-regression/test_settings_fanout2x2_.yml
  test-data-regression/test_settings_rotate_.yml
  tests/test_containers.py
Labels: bug

#2722 more_robust_updk_import
  gdsfactory/read/from_updk.py
Labels: maintenance

#2723 Add to svg
  gdsfactory/export/__init__.py
  gdsfactory/export/to_svg.py
Labels: enhancement

#2725 routing/get_bundle_sbend: Get input port dynamically
  gdsfactory/routing/get_bundle_sbend.py
Labels: bug

#2726 Improve layer stack
  gdsfactory/components/straight_heater_metal.py
  gdsfactory/export/to_3d.py
  gdsfactory/export/to_stl.py
  gdsfactory/export/to_svg.py
  gdsfactory/technology/layer_stack.py
  test-data-regression/test_settings_mzi_pads_center_.yml
  test-data-regression/test_settings_straight_heater_metal_.yml
  test-data-regression/test_settings_straight_heater_metal_90_90_.yml
  test-data-regression/test_settings_straight_heater_metal_undercut_90_90_.yml
  test-data-regression/test_settings_switch_tree_.yml
Labels: bug, enhancement

#2729 gf.path.extrude() Inset Fix
  gdsfactory/path.py
Labels: bug

#2727 removed deprecated pdk elements
  gdsfactory/components/straight_heater_metal.py
  gdsfactory/pdk.py
Labels: maintenance

#2730 CrossSection Factory
  gdsfactory/cross_section.py
  test-data-regression/test_settings_straight_heater_metal_undercut_90_90_.yml
Labels: bug

#2731 derived component has ports
  gdsfactory/technology/layer_stack.py
Labels: bug

#2732 Improve port types
  gdsfactory/component.py
  gdsfactory/components/C.py
  gdsfactory/components/dicing_lane.py
  test-data-regression/test_settings_C_.yml
Labels: maintenance

#2737 get_route_sbend allow mismatch
  gdsfactory/routing/get_route_sbend.py
Labels: routing, maintenance

#2739 auto_rename_ports for C
  gdsfactory/components/C.py
Labels: maintenance

#2742 fix spiral_inner_io add_grating_couplers
  gdsfactory/components/spiral_inner_io.py
Labels: bug

#2741 adds cross-section kwarg
  .changelog.d/2741.fixed
  gdsfactory/components/grating_coupler_array.py
Labels: maintenance

#2743 update ruff
  .pre-commit-config.yaml
  gdsfactory/component_layout.py
  gdsfactory/export/to_svg.py
Labels: maintenance

#2745 fix disk with wrap_angle=0
  gdsfactory/components/disk.py
Labels: bug

#2746 test other pdks
  .github/workflows/test_pdks.yml
  gdsfactory/components/grating_coupler_array.py
Labels: maintenance

#2748 Clean schematic
  gdsfactory/schematic.py
  gdsfactory/typings.py
  notebooks/10_schematic.ipynb
Labels: maintenance

#2751 add mimcap
  gdsfactory/components/__init__.py
  gdsfactory/components/mimcap.py
  pyproject.toml
  test-data-regression/test_settings_mimcap_.yml
  tests/test_schematic.py
Labels: enhancement

#2752 Improve get route astar
  gdsfactory/routing/get_route_astar.py
Labels: enhancement, routing

#2768 fixing docs
  docs/api.rst
  docs/api_routing.rst
  docs/components.rst
  gdsfactory/__init__.py
Labels: bug

#2769 Fix more docs
  Makefile
  docs/_toc.yml
  docs/api.rst
  gdsfactory/__init__.py
  gdsfactory/add_pins.py
  gdsfactory/component.py
  gdsfactory/component_layout.py
  gdsfactory/components/add_fiber_array_optical_south_electrical_north.py
  gdsfactory/components/component_sequence.py
  gdsfactory/components/pad.py
  gdsfactory/components/seal_ring.py
  gdsfactory/functions.py
  gdsfactory/grid.py
  gdsfactory/labels/__init__.py
  gdsfactory/labels/add_label_yaml.py
  gdsfactory/labels/ehva.py
  gdsfactory/labels/get_test_manifest.py
  gdsfactory/labels/write_labels.py
  gdsfactory/pack.py
  gdsfactory/path.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/routing/route_single.py
  gdsfactory/routing/route_single_from_steps.py
  gdsfactory/samples/pdk/test_fab_c/test_settings_mzi_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mzi_no_.yml
  gdsfactory/samples/sample_reticle.py
  gdsfactory/technology/layer_map.py
  gdsfactory/technology/layer_views.py
  notebooks/00_geometry.ipynb
  notebooks/01_references.ipynb
  notebooks/02_grid_snapping.ipynb
  notebooks/03_Path_CrossSection.ipynb
  notebooks/04_components_geometry.ipynb
  notebooks/04_components_pack.ipynb
  notebooks/04_components_shapes.ipynb
  notebooks/04_routing.ipynb
  notebooks/04_routing_electrical.ipynb
  notebooks/04_routing_non_manhattan.ipynb
  notebooks/07_mask.ipynb
  notebooks/08_pdk.ipynb
  notebooks/08_pdk_examples.ipynb
  notebooks/09_pdk_import.ipynb
  notebooks/11_best_practices.ipynb
  notebooks/rib_strip_autotransition.ipynb
  pyproject.toml
  test-data-regression/test_netlists_ring_single_array_.yml
  tests/labels/test_read_labels.py
  tests/routing/test_route_single_from_steps.py
  tests/technology/test_layer_views.py
  tests/technology/test_technology.py
  tests/test_paths_extrude.py
Labels: bug

#2772 add clear cache
  gdsfactory/__init__.py
  gdsfactory/component.py
  gdsfactory/components/add_trenches.py
  gdsfactory/components/component_sequence.py
  gdsfactory/components/cutback_loss.py
  gdsfactory/components/via_chain.py
  gdsfactory/config.py
  gdsfactory/samples/all_angle_routing.py
  notebooks/03_cells_autoname_and_cache.ipynb
Labels: enhancement

#2777 fix tech installation on windows
  gdsfactory/install.py
Labels: bug

#2784 update readme
  docs/developer.md
  pyproject.toml
Labels: documentation

#2788 New sort ports
  gdsfactory/component.py
  gdsfactory/components/add_fiber_array_optical_south_electrical_north.py
  gdsfactory/components/coh_rx_single_pol.py
  gdsfactory/get_netlist.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_bundle_all_angle.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/samples/06_remapping_layers.py
  gdsfactory/samples/30_lidar.py
  gdsfactory/samples/30_lidar_pcell.py
  gdsfactory/samples/30_route_bundle.py
  notebooks/04_routing.ipynb
  notebooks/10_schematic.ipynb
  notebooks/21_migration_guide_7_8.ipynb
  test-data-regression/test_connect_bundle_u_indirect.yml
  test-data-regression/test_connect_bundle_udirect.yml
  test-data-regression/test_import_gds_ports.yml
  test-data-regression/test_import_json_label.yml
  test-data-regression/test_route_bundle_obstacle.yml
  test-data-regression/test_route_bundle_optical.yml
  test-data-regression/test_route_bundle_sort_ports.yml
  test-data-regression/test_route_bundle_u_indirect_0_.yml
  test-data-regression/test_route_bundle_u_indirect_90_.yml
  test-data-regression/test_route_bundle_udirect.yml
  test-data-regression/test_route_bundle_udirect_pads.yml
  test-data-regression/test_route_south.yml
  test-data-regression/test_settings_cutback_splitter_.yml
  test-data-regression/test_settings_grating_coupler_rectangular_arbitrary_.yml
  test-data-regression/test_settings_pixel_.yml
  tests/components/test_extension.py
  tests/routing/test_port_ordering.py
  tests/routing/test_route_south.py
  tests/routing/test_routing_route_bundle.py
  tests/routing/test_routing_route_bundle_corner.py
  tests/routing/test_routing_route_bundle_electrical.py
  tests/routing/test_routing_route_bundle_electrical_multilayer.py
  tests/routing/test_routing_route_bundle_obstacle.py
  tests/routing/test_routing_route_bundle_optical.py
  tests/routing/test_routing_route_bundle_sbend_routing.py
  tests/routing/test_routing_route_bundle_sort_ports.py
  tests/routing/test_routing_route_bundle_udirect.py
  tests/routing/test_routing_route_bundle_uindirect.py
  tests/routing/test_routing_route_bundle_west_to_north.py
  tests/test_cross_section.py
  tests/test_get_netlist.py
  tests/test_netlist_electrical.py
  tests/test_netlist_with_routes.py
Labels: enhancement, routing

#2785 add __getattribute__ to gf.Component
  gdsfactory/__init__.py
  gdsfactory/cli.py
  gdsfactory/component.py
  gdsfactory/config.py
  gdsfactory/cross_section.py
  gdsfactory/difftest.py
  gdsfactory/get_factories.py
  gdsfactory/labels/write_labels.py
  gdsfactory/pdk.py
  gdsfactory/read/from_gdspaths.py
  gdsfactory/technology/layer_views.py
  gdsfactory/write_cells.py
Labels: enhancement

#2792 keep shorter name for PDK
  README.md
  gdsfactory/difftest.py
Labels: documentation

#2794 Deprecate instance setter
  gdsfactory/add_pins.py
  gdsfactory/component.py
  gdsfactory/components/bend_s.py
  gdsfactory/components/bezier.py
  gdsfactory/components/coupler_asymmetric.py
  gdsfactory/components/dbr.py
  gdsfactory/components/straight.py
  gdsfactory/get_netlist.py
  tests/test_add_pins.py
  tests/test_add_ports.py
Labels: enhancement

#2798 More fixes
  gdsfactory/components/edge_coupler_array.py
  gdsfactory/get_netlist.py
  gdsfactory/samples/30_lidar.py
  gdsfactory/samples/30_lidar_with_pads.py
  gdsfactory/serialization.py
  notebooks/04_components_hierarchy.ipynb
Labels: bug

#2800 make "-" boolean_not
  gdsfactory/component.py
Labels: bug

#2802 Fix tests2
  README.md
  gdsfactory/add_pins.py
  gdsfactory/components/dicing_lane.py
  tests/labels/test_read_labels.py
  tests/test_add_ports.py
Labels: bug, documentation

#2806 add route_info
  gdsfactory/components/bend_circular.py
  gdsfactory/components/bend_euler.py
  gdsfactory/components/bezier.py
  gdsfactory/components/coupler_ring.py
  gdsfactory/components/mzit.py
  gdsfactory/components/ring_double.py
  gdsfactory/components/ring_single.py
  gdsfactory/samples/netlists/bend_mirror.yml
  gdsfactory/samples/netlists/bend_translated_rotated.yml
  gdsfactory/technology/layer_stack.py
  notebooks/04_routing.ipynb
  test-data-regression/test_netlists_mzit_.yml
  test-data-regression/test_netlists_ring_single_.yml
  test-data-regression/test_route_bundle_u_direct_different_x.yml
  test-data-regression/test_settings_add_trenches90_.yml
  test-data-regression/test_settings_bend_circular180_.yml
  test-data-regression/test_settings_bend_circular_.yml
  test-data-regression/test_settings_bend_euler180_.yml
  test-data-regression/test_settings_bend_euler_.yml
  test-data-regression/test_settings_bend_euler_trenches_.yml
  test-data-regression/test_settings_bend_s_.yml
  test-data-regression/test_settings_bezier_.yml
  tests/routing/test_routing_route_bundle_all_angle.py
  tests/technology/test_layerstack.py
  tests/test_component.py
  tests/test_get_netlist_yaml.py
  tests/test_get_netlist_yaml2.py
  tests/test_get_netlist_yaml4.py
  tests/test_get_netlist_yaml5.py
  tests/test_netlists.py
  tests/test_paths_extrude.py
Labels: enhancement
