Repository gdsfactory/gdsfactory, pull requests merged in 2024-01, with the labels that each got.

#2450 Add helper function for changing nested partial parameters
  gdsfactory/functions.py
  tests/test_change_keywords_in_nested_partials.py
Labels: python

#2434 better naming
  gdsfactory/add_pins.py
  gdsfactory/component.py
  gdsfactory/samples/07_flattening_device.py
  gdsfactory/serialization.py
  test-data-regression/test_import_json_label.yml
  test-data-regression/test_import_ports_center.yml
  test-data-regression/test_import_ports_inside.yml
  test-data-regression/test_import_ports_siepic.yml
  test-data-regression/test_netlists_sample_doe_function_.yml
  test-data-regression/test_settings_add_electrical_pads_shortest_.yml
  test-data-regression/test_settings_add_electrical_pads_top_.yml
  test-data-regression/test_settings_add_fiber_single_.yml
  test-data-regression/test_settings_add_padding_container_.yml
  test-data-regression/test_settings_add_pads_bot_.yml
  test-data-regression/test_settings_add_pads_top_.yml
  test-data-regression/test_settings_fanout2x2_.yml
  test-data-regression/test_settings_rotate_.yml
  tests/test_clear_cache.py
  tests/test_components.py
  tests/test_flatten.py
  tests/test_import_gds_markers.py
  tests/test_paths_extrude.py
Labels: help wanted

#2457 Fix release drafter to properly use gdsfactory project labels
  .github/release-drafter.yml
Labels: github_actions

#2458 add gf.functions.add_marker_layer_container
  gdsfactory/functions.py
Labels: enhancement
