Repository gdsfactory/gdsfactory, pull requests merged in 2024-02, with the labels that each got.

#2515 add autolabeler
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/require-labels.yml
Labels: github_actions

#2516 fix docker build
  .devcontainer/Dockerfile.dev
  .devcontainer/Dockerfile.dev_minimal
  .devcontainer/Makefile
Labels: bug

#2518 Centering vias in 45degree via stack
  gdsfactory/components/via_stack.py
Labels: bug

#2519 publish docker to github
  .devcontainer/Dockerfile.dev
  .devcontainer/Dockerfile.dev_minimal
  .github/workflows/docker.yml
Labels: github_actions

#2521 improve docker
  .github/workflows/docker.yml
  .github/workflows/stale.yml
  README.md
  docs/developer.md
  gdsfactory/cell.py
  test-data-regression/test_settings_add_padding_container_.yml
Labels: documentation

#2525 fix gdsfactory full
  pyproject.toml
Labels: bug, github_actions

#2524 add post process to more pcells
  gdsfactory/components/coupler.py
  gdsfactory/components/coupler_straight.py
  gdsfactory/components/resistance_sheet.py
  gdsfactory/components/triangles.py
  gdsfactory/components/via_stack.py
  test-data-regression/test_netlists_mzit_.yml
  test-data-regression/test_settings_coupler_.yml
  test-data-regression/test_settings_resistance_sheet_.yml
  test-data-regression/test_settings_triangle_.yml
  test-data-regression/test_settings_via_stack_.yml
  test-data-regression/test_settings_via_stack_heater_m2_.yml
  test-data-regression/test_settings_via_stack_heater_m3_.yml
  test-data-regression/test_settings_via_stack_heater_mtop_.yml
  test-data-regression/test_settings_via_stack_slab_m3_.yml
Labels: enhancement

#2528 fix seal_ring spacing
  gdsfactory/components/seal_ring.py
Labels: bug

#2529 fix extrude
  CHANGELOG.md
  gdsfactory/path.py
Labels: bug, documentation, maintenance

#2530 more post_process
  gdsfactory/components/cross.py
  gdsfactory/components/pad.py
  gdsfactory/components/straight_heater_meander.py
  test-data-regression/test_netlists_sample_different_link_factory_.yml
  test-data-regression/test_netlists_sample_waypoints_.yml
  test-data-regression/test_settings_cross_.yml
  test-data-regression/test_settings_pad_.yml
  test-data-regression/test_settings_pad_array0_.yml
  test-data-regression/test_settings_pad_array180_.yml
  test-data-regression/test_settings_pad_array270_.yml
  test-data-regression/test_settings_pad_array90_.yml
  test-data-regression/test_settings_pad_array_.yml
  test-data-regression/test_settings_pad_rectangular_.yml
  test-data-regression/test_settings_spiral_meander_.yml
  test-data-regression/test_settings_straight_heater_meander_.yml
Labels: maintenance

#2531 post_process
  gdsfactory/components/mmi.py
  gdsfactory/components/mmi1x2.py
  gdsfactory/components/mmi1x2_with_sbend.py
  gdsfactory/components/mmi2x2.py
  gdsfactory/components/mmi2x2_with_sbend.py
  gdsfactory/components/mzi.py
  gdsfactory/read/import_gds.py
  gdsfactory/samples/pdk/test_fab_c/test_settings_mmi1x2_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mmi1x2_no_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mzi_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mzi_no_.yml
  test-data-regression/test_netlists_sample_docstring_.yml
  test-data-regression/test_netlists_sample_mmis_.yml
  test-data-regression/test_netlists_yaml_anchor_.yml
  test-data-regression/test_read_gds_with_settings2.yml
  test-data-regression/test_settings_add_electrical_pads_shortest_.yml
  test-data-regression/test_settings_add_electrical_pads_top_.yml
  test-data-regression/test_settings_add_fiber_single_.yml
  test-data-regression/test_settings_add_padding_container_.yml
  test-data-regression/test_settings_add_pads_bot_.yml
  test-data-regression/test_settings_add_pads_top_.yml
  test-data-regression/test_settings_fanout2x2_.yml
  test-data-regression/test_settings_mmi1x2_.yml
  test-data-regression/test_settings_mmi1x2_with_sbend_.yml
  test-data-regression/test_settings_mmi2x2_.yml
  test-data-regression/test_settings_mmi2x2_with_sbend_.yml
  test-data-regression/test_settings_mmi_.yml
  test-data-regression/test_settings_mzi1x2_2x2_.yml
  test-data-regression/test_settings_mzi2x2_2x2_.yml
  test-data-regression/test_settings_mzi2x2_2x2_phase_shifter_.yml
  test-data-regression/test_settings_mzi_.yml
  test-data-regression/test_settings_mzi_coupler_.yml
  test-data-regression/test_settings_mzi_phase_shifter_.yml
  test-data-regression/test_settings_rotate_.yml
  tests/gds/mzi2x2.gds
  tests/gds/mzi2x2.yml
Labels: maintenance

#2532 add post_process to bezier
  gdsfactory/components/bezier.py
  test-data-regression/test_settings_bezier_.yml
Labels: enhancement, maintenance

#2533 add docs and development packages to docker container
  .devcontainer/Dockerfile.dev
  pyproject.toml
Labels: enhancement, maintenance

#2535 Add possibility of adding label when adding fiber array
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/typings.py
Labels: enhancement, routing, maintenance

#2543 Possibility of specifying offset in add_fiber_array
  gdsfactory/routing/add_fiber_array.py
Labels: routing, maintenance

#2542 better annotations
  gdsfactory/components/seal_ring.py
  gdsfactory/routing/get_bundle_from_steps.py
  gdsfactory/routing/get_route_from_steps.py
  gdsfactory/routing/path_length_matching.py
Labels: maintenance

#2544 fixes to kfactory interface as well as show_ports with None orientation
  gdsfactory/add_pins.py
  gdsfactory/components/pad.py
  gdsfactory/export/to_kfactory.py
Labels: bug, maintenance

#2546 add more post_proces
  gdsfactory/routing/add_electrical_pads_top.py
  gdsfactory/routing/add_electrical_pads_top_dc.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/routing/add_pads.py
  test-data-regression/test_import_json_label.yml
  test-data-regression/test_settings_add_electrical_pads_top_.yml
  test-data-regression/test_settings_add_fiber_single_.yml
  test-data-regression/test_settings_add_pads_bot_.yml
Labels: enhancement, maintenance

#2547 fix typos
  gdsfactory/routing/add_electrical_pads_top.py
  gdsfactory/routing/add_electrical_pads_top_dc.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/routing/add_pads.py
  test-data-regression/test_import_json_label.yml
  test-data-regression/test_settings_add_electrical_pads_top_.yml
  test-data-regression/test_settings_add_fiber_single_.yml
  test-data-regression/test_settings_add_pads_bot_.yml
Labels: bug, maintenance

#2550 Snap lengths to 2dbu
  CHANGELOG.md
  gdsfactory/add_pins.py
  gdsfactory/component.py
  gdsfactory/components/compass.py
  gdsfactory/components/coupler_bent.py
  gdsfactory/components/grating_coupler_elliptical.py
  gdsfactory/components/grating_coupler_elliptical_arbitrary.py
  gdsfactory/components/grating_coupler_elliptical_trenches.py
  gdsfactory/components/mode_converter.py
  gdsfactory/components/regular_polygon.py
  gdsfactory/components/spiral_inner_io.py
  gdsfactory/components/straight.py
  gdsfactory/config.py
  gdsfactory/cross_section.py
  gdsfactory/path.py
  gdsfactory/port.py
  gdsfactory/samples/snap_bends.py
  gdsfactory/serialization.py
  notebooks/02_grid_snapping.ipynb
  test-data-regression/test_label_fiber_single_custom.csv
  test-data-regression/test_netlists_sample_doe_function_.yml
  test-data-regression/test_netlists_sample_mmis_.yml
  test-data-regression/test_settings_grating_coupler_elliptical_lumerical_.yml
  test-data-regression/test_settings_hexagon_.yml
  test-data-regression/test_settings_octagon_.yml
  test-data-regression/test_settings_regular_polygon_.yml
  test-data-regression/test_settings_spiral_racetrack_fixed_length_.yml
  tests/routing/test_routing_get_bundle_all_angle.py
  tests/test_add_pins.py
  tests/test_component.py
  tests/test_components.py
  tests/test_paths.py
  tests/test_serialize_json.py
  tests/test_shear_face_path.py
Labels: documentation, feature, minor

#2551 remove test_offset
  tests/test_offset.py
Labels: maintenance

#2552 Make CrossSection hashable
  gdsfactory/cross_section.py
Labels: maintenance

#2553 round widths to 2nm when extruding
  gdsfactory/component.py
  gdsfactory/components/taper.py
  gdsfactory/path.py
  test-data-regression/test_label_fiber_single_custom.csv
  test-data-regression/test_netlists_sample_doe_function_.yml
  test-data-regression/test_netlists_sample_mmis_.yml
  test-data-regression/test_settings_spiral_racetrack_fixed_length_.yml
  tests/test_component_from_yaml.py
  tests/test_cross_section.py
  tests/test_paths.py
Labels: maintenance

#2559 add via_chain
  gdsfactory/components/__init__.py
  gdsfactory/components/via_chain.py
  gdsfactory/components/via_cutback.py
  gdsfactory/components/via_stack.py
  gdsfactory/generic_tech/klayout/layers.lyp
  gdsfactory/generic_tech/klayout/tech.lyt
  gdsfactory/generic_tech/layer_views.yaml
  test-data-regression/test_settings_via_chain_.yml
  test-data-regression/test_settings_via_cutback_.yml
Labels: enhancement

#2565 fix taper extrude
  gdsfactory/components/taper.py
Labels: bug, maintenance

#2570 Allow for different cross sections in cdsem
  gdsfactory/components/cdsem_straight_density.py
Labels: maintenance
