Repository gdsfactory/gdsfactory, pull requests merged in 2024-10, with the labels that each got.

#3234 Improve edge coupler docs and fix grid_with_text
  gdsfactory/grid.py
  gdsfactory/samples/34_route_edge_coupler.py
  gdsfactory/samples/34_route_edge_coupler_bend_s.py
  notebooks/04_routing_electrical.ipynb
Labels: bug, documentation

#3238 better yaml error messages when component missing from pdk
  gdsfactory/pdk.py
  gdsfactory/read/from_yaml.py
Labels: enhancement

#3224 enable waypoints
  gdsfactory/routing/route_bundle.py
  notebooks/04_routing.ipynb
Labels: enhancement

#3240 Remove taper from electrical routing
  gdsfactory/routing/route_single_from_steps.py
Labels: bug

#3243 remove cross_section arg from kwargs in taper function
  gdsfactory/components/taper.py
  test-data-regression/test_netlists_taper_nc_sc_.yml
  test-data-regression/test_netlists_taper_sc_nc_.yml
  test-data-regression/test_settings_taper_nc_sc_.yml
  test-data-regression/test_settings_taper_sc_nc_.yml
Labels: maintenance

#3246 Fix radius loopback
  gdsfactory/components/cutback_2x2.py
  gdsfactory/components/extension.py
  gdsfactory/routing/route_fiber_array.py
  test-data-regression/test_netlists_edge_coupler_array_with_loopback_.yml
  test-data-regression/test_netlists_extend_ports_.yml
  test-data-regression/test_settings_extend_ports_.yml
Labels: bug

#3248 Add steps to route single
  docs/api_routing.rst
  gdsfactory/components/grating_coupler_loss.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/routing/route_single.py
  gdsfactory/routing/route_single_from_steps.py
  notebooks/04_routing.ipynb
  notebooks/04_routing_electrical.ipynb
  test-data-regression/test_settings_fiber_single_.yml
  test-data-regression/test_settings_type1_.yml
  test-data-regression/test_settings_type2_.yml
  tests/routing/test_add_fiber_array.py
  tests/routing/test_route_single_error.py
  tests/routing/test_route_single_from_steps.py
Labels: enhancement

#3249 add missing layers
  gdsfactory/component.py
Labels: maintenance

#3250 Keep port names from component
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/routing/route_fiber_array.py
  tests/routing/test_add_fiber_array.py
Labels: enhancement

#3253 Add fiber array without route south
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/auto_taper.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/routing/route_south.py
  gdsfactory/samples/big_device_electrical.py
  gdsfactory/samples/sample_reticle.py
  notebooks/04_routing_electrical.ipynb
Labels: enhancement, routing

#3254 fix straight function
  gdsfactory/components/cutback_2x2.py
  gdsfactory/components/cutback_bend.py
  gdsfactory/components/cutback_component.py
  gdsfactory/routing/route_fiber_array.py
  test-data-regression/test_netlists_cutback_component_mirror_.yml
  test-data-regression/test_settings_cutback_2x2_.yml
  test-data-regression/test_settings_cutback_component_.yml
  test-data-regression/test_settings_cutback_component_mirror_.yml
Labels: bug

#3255 fix route_single
  gdsfactory/routing/route_single.py
  tests/routing/test_route_single_from_steps.py
Labels: bug

#3256 define allowed port_types in gf.CONF.port_types and warn other types
  gdsfactory/component.py
  gdsfactory/config.py
  notebooks/01_references.ipynb
Labels: maintenance

#3260 cleanup_routing
  gdsfactory/components/add_fiber_array_optical_south_electrical_north.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/route_fiber_array.py
  notebooks/04_routing_electrical.ipynb
  test-data-regression/test_settings_sample_fiber_array_.yml
  test-data-regression/test_settings_sample_fiber_single_.yml
  tests/routing/test_add_fiber_array.py
Labels: enhancement

#3262 update kfactory
  gdsfactory/components/extension.py
  gdsfactory/write_cells.py
  notebooks/09_pdk_import.ipynb
  pyproject.toml
  tests/test_write_cells.py
Labels: dependencies

#3264 allow_routing_around_bboxes
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/route_fiber_array.py
Labels: routing, maintenance

#3267 Snap ports to 2nm in functions to detect ports
  .github/ISSUE_TEMPLATE/bug_report.md
  gdsfactory/add_ports.py
Labels: bug, documentation

#3268 fix dbx and dby
  CHANGELOG.md
  gdsfactory/read/from_yaml.py
Labels: bug, documentation

#3272 fix grating_coupler_elliptical_trenches
  gdsfactory/components/grating_coupler_elliptical_trenches.py
  test-data-regression/test_netlists_die_with_pads_.yml
  test-data-regression/test_netlists_grating_coupler_elliptical_trenches_.yml
  test-data-regression/test_netlists_grating_coupler_loss_fiber_array_.yml
  test-data-regression/test_netlists_grating_coupler_te_.yml
  test-data-regression/test_netlists_grating_coupler_tm_.yml
  test-data-regression/test_netlists_loss_deembedding_ch12_34_.yml
  test-data-regression/test_netlists_loss_deembedding_ch13_24_.yml
  test-data-regression/test_netlists_loss_deembedding_ch14_23_.yml
  test-data-regression/test_settings_grating_coupler_elliptical_trenches_.yml
  test-data-regression/test_settings_grating_coupler_te_.yml
  test-data-regression/test_settings_grating_coupler_tm_.yml
Labels: bug

#3275 add move_port function
  gdsfactory/functions.py
Labels: enhancement, maintenance

#3278 make GDSFactory backwards compatible with older kfactory versions
  gdsfactory/read/import_gds.py
Labels: bug

#3279 use uv
  .github/workflows/pages.yml
  .github/workflows/test_code.yml
  .github/workflows/test_pdks.yml
  .gitignore
  Makefile
Labels: maintenance, github_actions

#3282 fix test_pdks
  .github/workflows/test_pdks.yml
Labels: bug

#3283 Remove default cross section
  gdsfactory/components/awg.py
  gdsfactory/components/coh_rx_single_pol.py
  gdsfactory/components/loop_mirror.py
  gdsfactory/components/straight.py
  gdsfactory/components/straight_heater_meander_doped.py
  gdsfactory/read/from_yaml.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_single.py
  gdsfactory/samples/13_component_netlist.py
  notebooks/04_routing.ipynb
  notebooks/04_routing_electrical.ipynb
  notebooks/10_schematic.ipynb
  notebooks/10_yaml_component.ipynb
  notebooks/21_migration_guide_7_8.ipynb
  notebooks/yaml_pics/routes.pic.yml
  notebooks/yaml_pics/routes_mmi.pic.yml
  notebooks/yaml_pics/routes_path_length_match.pic.yml
  test-data-regression/test_netlists_awg_.yml
  test-data-regression/test_netlists_coh_rx_single_pol_.yml
  test-data-regression/test_netlists_grating_coupler_tree_.yml
  test-data-regression/test_netlists_loop_mirror_.yml
  test-data-regression/test_settings_awg_.yml
  test-data-regression/test_settings_loop_mirror_.yml
  tests/read/test_component_from_yaml.py
  tests/routing/test_port_ordering.py
  tests/routing/test_route_single_error.py
  tests/routing/test_route_single_from_steps.py
  tests/routing/test_routing_route_bundle.py
  tests/routing/test_routing_route_bundle_corner.py
  tests/routing/test_routing_route_bundle_obstacle.py
  tests/routing/test_routing_route_bundle_optical.py
  tests/routing/test_routing_route_bundle_sort_ports.py
  tests/routing/test_routing_route_bundle_u_direct_different_x.py
  tests/routing/test_routing_route_bundle_udirect.py
  tests/routing/test_routing_route_bundle_uindirect.py
Labels: enhancement, routing

#3285 update kfactory to 0.21.1 and bring back python3.10 compat
  .github/workflows/test_code.yml
  pyproject.toml
Labels: bug

#3286 better error messages for routing issues for routing issues
  gdsfactory/routing/auto_taper.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_single.py
Labels: bug, documentation

#3287 Componenteference: fixing typo and potential bug
  gdsfactory/component.py
Labels: bug

#3291 add optional add pin layer
  gdsfactory/add_pins.py
  gdsfactory/config.py
  gdsfactory/port.py
Labels: enhancement

#3292 update kfactory
  pyproject.toml
Labels: dependencies

#3293 update_kfactory0.21.4
  gdsfactory/routing/route_bundle.py
  notebooks/04_routing.ipynb
  notebooks/04_routing_electrical.ipynb
  pyproject.toml
Labels: dependencies

#3294 improve route_bundle
  gdsfactory/routing/route_bundle.py
  test-data-regression/test_route_bundle_obstacle.yml
  test-data-regression/test_route_bundle_udirect_pads.yml
  test-data-regression/test_route_bundle_west_to_north.yml
  test-data-regression/test_route_bundle_west_to_north2.yml
  tests/read/test_component_from_yaml.py
Labels: routing, maintenance

#3295 fix grid with ports and add test
  gdsfactory/grid.py
  tests/test_grid.py
Labels: bug

#3298 fix yaml load
  gdsfactory/read/from_yaml.py
Labels: bug

#3299 Update layer_views.py
  gdsfactory/technology/layer_views.py
Labels: bug

#3301 add some type hints
  gdsfactory/add_padding.py
  gdsfactory/cell.py
  gdsfactory/component.py
  gdsfactory/export/to_3d.py
  gdsfactory/path.py
  gdsfactory/pdk.py
  gdsfactory/port.py
  gdsfactory/py.typed
  gdsfactory/routing/route_bundle.py
  gdsfactory/typings.py
Labels: documentation, enhancement

#3305 add width to Component.info
  gdsfactory/components/bend_circular.py
  gdsfactory/components/bend_euler.py
  gdsfactory/read/from_yaml.py
  pyproject.toml
  test-data-regression/test_netlists_awg_.yml
  test-data-regression/test_netlists_bend_euler_s_.yml
  test-data-regression/test_netlists_coh_rx_single_pol_.yml
  test-data-regression/test_netlists_coh_tx_dual_pol_.yml
  test-data-regression/test_netlists_coh_tx_single_pol_.yml
  test-data-regression/test_netlists_coupler90_.yml
  test-data-regression/test_netlists_coupler90circular_.yml
  test-data-regression/test_netlists_coupler_broadband_.yml
  test-data-regression/test_netlists_cutback_bend180_.yml
  test-data-regression/test_netlists_cutback_bend90_.yml
  test-data-regression/test_netlists_cutback_bend90circular_.yml
  test-data-regression/test_netlists_cutback_bend_.yml
  test-data-regression/test_netlists_cutback_component_mirror_.yml
  test-data-regression/test_netlists_cutback_splitter_.yml
  test-data-regression/test_netlists_delay_snake_sbend_.yml
  test-data-regression/test_netlists_edge_coupler_array_with_loopback_.yml
  test-data-regression/test_netlists_grating_coupler_loss_fiber_array_.yml
  test-data-regression/test_netlists_grating_coupler_tree_.yml
  test-data-regression/test_netlists_loop_mirror_.yml
  test-data-regression/test_netlists_loss_deembedding_ch12_34_.yml
  test-data-regression/test_netlists_loss_deembedding_ch13_24_.yml
  test-data-regression/test_netlists_loss_deembedding_ch14_23_.yml
  test-data-regression/test_netlists_mzi1x2_2x2_.yml
  test-data-regression/test_netlists_mzi2x2_2x2_.yml
  test-data-regression/test_netlists_mzi2x2_2x2_phase_shifter_.yml
  test-data-regression/test_netlists_mzi_.yml
  test-data-regression/test_netlists_mzi_arm_.yml
  test-data-regression/test_netlists_mzi_coupler_.yml
  test-data-regression/test_netlists_mzi_phase_shifter_.yml
  test-data-regression/test_netlists_mzi_phase_shifter_top_heater_metal_.yml
  test-data-regression/test_netlists_mzi_pin_.yml
  test-data-regression/test_netlists_mzit_.yml
  test-data-regression/test_netlists_mzm_.yml
  test-data-regression/test_netlists_ring_crow_couplers_.yml
  test-data-regression/test_netlists_ring_single_.yml
  test-data-regression/test_netlists_ring_single_dut_.yml
  test-data-regression/test_netlists_ring_single_heater_.yml
  test-data-regression/test_netlists_spiral_.yml
  test-data-regression/test_netlists_splitter_tree_.yml
  test-data-regression/test_netlists_staircase_.yml
  test-data-regression/test_netlists_switch_tree_.yml
  test-data-regression/test_route_bundle_obstacle.yml
  test-data-regression/test_route_bundle_udirect_pads.yml
  test-data-regression/test_route_bundle_west_to_north.yml
  test-data-regression/test_route_bundle_west_to_north2.yml
  test-data-regression/test_settings_add_trenches90_.yml
  test-data-regression/test_settings_bend_circular180_.yml
  test-data-regression/test_settings_bend_circular_.yml
  test-data-regression/test_settings_bend_euler180_.yml
  test-data-regression/test_settings_bend_euler_.yml
  tests/read/test_component_from_yaml.py
Labels: enhancement

#3308 Fix `Component.get_labels` returns texts in wrong locations
  gdsfactory/component.py
  gdsfactory/pdk.py
Labels: bug

#3309 add flatten section to docs
  notebooks/04_components_geometry.ipynb
Labels: enhancement

#3315 install klive with git
  gdsfactory/install.py
Labels: bug

#3316 update readme
  README.md
Labels: documentation

#3318 More consitent cutback parameters
  gdsfactory/components/cutback_bend.py
  test-data-regression/test_settings_cutback_bend180_.yml
  test-data-regression/test_settings_cutback_bend180circular_.yml
  test-data-regression/test_settings_cutback_bend90_.yml
  test-data-regression/test_settings_cutback_bend90circular_.yml
  test-data-regression/test_settings_cutback_bend_.yml
  test-data-regression/test_settings_staircase_.yml
Labels: maintenance

#3321 allow multiple connections in get_netlist
  gdsfactory/get_netlist.py
Labels: maintenance

#3322 fix via_bbox_offsets
  gdsfactory/components/via.py
  test-data-regression/test_netlists_via1_.yml
  test-data-regression/test_netlists_via2_.yml
  test-data-regression/test_netlists_via_.yml
  test-data-regression/test_netlists_via_chain_.yml
  test-data-regression/test_netlists_via_stack_.yml
  test-data-regression/test_netlists_via_stack_heater_m3_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_mini_.yml
  test-data-regression/test_netlists_via_stack_m1_mtop_.yml
  test-data-regression/test_netlists_via_stack_npp_m1_.yml
  test-data-regression/test_netlists_via_stack_slab_m1_horizontal_.yml
  test-data-regression/test_netlists_via_stack_slab_m3_.yml
  test-data-regression/test_netlists_via_stack_slab_npp_m3_.yml
  test-data-regression/test_netlists_via_stack_with_offset_.yml
  test-data-regression/test_netlists_viac_.yml
  test-data-regression/test_settings_via1_.yml
  test-data-regression/test_settings_via2_.yml
  test-data-regression/test_settings_via_.yml
  test-data-regression/test_settings_viac_.yml
  tests/read/test_component_from_yaml.py
  tests/test_get_netlist.py
Labels: bug

#3323 fix difftest
  gdsfactory/difftest.py
Labels: bug

#3304 remove deprecation warnings
  gdsfactory/component.py
  gdsfactory/generic_tech/klayout/grain.xml
  notebooks/21_migration_guide_7_8.ipynb
Labels: enhancement

#3325 improve docs after dbu
  notebooks/00_geometry.ipynb
  notebooks/01_references.ipynb
  notebooks/03_Path_CrossSection.ipynb
  notebooks/04_routing.ipynb
  notebooks/21_migration_guide_7_8.ipynb
Labels: documentation

#3324 bump kfactory
  notebooks/00_geometry.ipynb
  notebooks/01_references.ipynb
  notebooks/03_Path_CrossSection.ipynb
  notebooks/03_cells_autoname_and_cache.ipynb
  notebooks/04_components_geometry.ipynb
  notebooks/04_routing.ipynb
  notebooks/04_routing_electrical.ipynb
  notebooks/11_best_practices.ipynb
  notebooks/21_migration_guide_7_8.ipynb
  pyproject.toml
Labels: dependencies

#3328 update get cells function
  gdsfactory/cell.py
  gdsfactory/components/triangles.py
  gdsfactory/get_factories.py
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_no_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_sc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_so_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_gc_sc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mmi1x2_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mmi1x2_no_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mmi1x2_sc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_mmi1x2_so_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_no_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_sc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_so_.yml
  test-data-regression/test_netlists_triangle2_.yml
  test-data-regression/test_netlists_triangle4_.yml
  test-data-regression/test_settings_triangle2_.yml
  test-data-regression/test_settings_triangle4_.yml
Labels: enhancement, maintenance
