Repository gdsfactory/gdsfactory, pull requests merged in 2024-12, with the labels that each got.

#3446 rename_pad_spacing_to_pad_pitch
  gdsfactory/components/add_fiber_array_optical_south_electrical_north.py
  gdsfactory/components/greek_cross.py
  gdsfactory/components/mzi_pads_center.py
  gdsfactory/components/pad_gsg.py
  gdsfactory/components/pads_shorted.py
  gdsfactory/generic_tech/cells.py
  gdsfactory/pdk.py
  gdsfactory/routing/add_pads.py
  test-data-regression/test_netlists_greek_cross_with_pads_.yml
  test-data-regression/test_netlists_mzi_pads_center_.yml
  test-data-regression/test_netlists_pad_gsg_open_.yml
  test-data-regression/test_netlists_pad_gsg_short_.yml
  test-data-regression/test_netlists_pads_shorted_.yml
  test-data-regression/test_settings_add_fiber_array_optical_south_electrical_north_.yml
  test-data-regression/test_settings_add_pads_bot_.yml
  test-data-regression/test_settings_greek_cross_with_pads_.yml
  test-data-regression/test_settings_mzi_pads_center_.yml
  test-data-regression/test_settings_pad_gsg_open_.yml
  test-data-regression/test_settings_pad_gsg_short_.yml
  test-data-regression/test_settings_pads_shorted_.yml
  test-data-regression/test_settings_via_cutback_.yml
Labels: maintenance

#3447 better type annotation
  gdsfactory/components/text_rectangular.py
Labels: maintenance

#3448 rename_fiber_spacing_to_pitch
  gdsfactory/components/add_fiber_array_optical_south_electrical_north.py
  gdsfactory/pdk.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_fiber_single.py
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/samples/01_component_pcell_with_parameters.py
  test-data-regression/test_settings_add_fiber_array_optical_south_electrical_north_.yml
Labels: maintenance

#3450 add uv-precommit
  .pre-commit-config.yaml
  uv.lock
Labels: enhancement

#3454 add offset
  gdsfactory/component.py
  gdsfactory/components/crossing_waveguide.py
  test-data-regression/test_netlists_crossing45_.yml
  tests/components/test_netlists.py
  tests/routing/test_routing_route_bundle_west_to_north.py
Labels: enhancement

#3453 Fix MyPy issues in export folder
  gdsfactory/component.py
  gdsfactory/export/to_3d.py
  gdsfactory/export/to_gerber.py
  gdsfactory/export/to_np.py
  gdsfactory/export/to_stl.py
  gdsfactory/functions.py
  gdsfactory/technology/layer_stack.py
  pyproject.toml
Labels: maintenance, code quaility

#3459 Fix mypy errors in generic_tech and technology folders
  gdsfactory/cross_section.py
  gdsfactory/generic_tech/__init__.py
  gdsfactory/generic_tech/klayout/lvs/run_lvs.py
  gdsfactory/generic_tech/klayout/python/kgdsfactory/__init__.py
  gdsfactory/pdk.py
  gdsfactory/technology/klayout_tech.py
  gdsfactory/technology/layer_stack.py
  gdsfactory/technology/layer_views.py
  gdsfactory/technology/processes.py
  gdsfactory/technology/yaml_utils.py
  gdsfactory/typings.py
Labels: maintenance

#3458 Less kwargs2
  gdsfactory/components/cdsem_coupler.py
  gdsfactory/components/coupler90.py
  gdsfactory/components/coupler_full.py
  test-data-regression/test_netlists_cdsem_coupler_.yml
  test-data-regression/test_netlists_coupler90_.yml
  test-data-regression/test_netlists_coupler90circular_.yml
  test-data-regression/test_netlists_coupler_full_.yml
  test-data-regression/test_settings_cdsem_coupler_.yml
  test-data-regression/test_settings_coupler90_.yml
  test-data-regression/test_settings_coupler90circular_.yml
  test-data-regression/test_settings_coupler_full_.yml
Labels: maintenance

#3460 remove dup
  gdsfactory/components/extension.py
  gdsfactory/components/mzi_arm.py
  gdsfactory/components/mzi_arms.py
  test-data-regression/test_netlists_extend_ports_.yml
Labels: maintenance

#3461 Less kwargs3
  gdsfactory/components/delay_snake.py
  gdsfactory/components/delay_snake2.py
  gdsfactory/components/delay_snake_sbend.py
  gdsfactory/components/grating_coupler_dual_pol.py
  gdsfactory/components/grating_coupler_elliptical.py
  gdsfactory/components/straight_pin_slot.py
  gdsfactory/components/taper_cross_section.py
  test-data-regression/test_netlists_delay_snake_sbend_.yml
  test-data-regression/test_netlists_straight_pin_slot_.yml
  test-data-regression/test_settings_delay_snake2_.yml
  test-data-regression/test_settings_delay_snake_.yml
  test-data-regression/test_settings_delay_snake_sbend_.yml
  test-data-regression/test_settings_straight_pin_slot_.yml
Labels: maintenance

#3462 Fix mypy errors in labels and read folders
  gdsfactory/__init__.py
  gdsfactory/add_pins.py
  gdsfactory/config.py
  gdsfactory/labels/add_labels.py
  gdsfactory/labels/ehva.py
  gdsfactory/labels/write_test_manifest.py
  gdsfactory/port.py
  gdsfactory/read/from_gdspaths.py
  gdsfactory/read/from_np.py
  gdsfactory/read/from_updk.py
  gdsfactory/read/from_yaml.py
  gdsfactory/read/from_yaml_template.py
  gdsfactory/read/import_gds.py
  gdsfactory/typings.py
Labels: maintenance

#3464 Fix MyPy erros in routing folder
  gdsfactory/_deprecation.py
  gdsfactory/components/add_fiber_array_optical_south_electrical_north.py
  gdsfactory/cross_section.py
  gdsfactory/labels/get_test_manifest.py
  gdsfactory/path.py
  gdsfactory/pdk.py
  gdsfactory/port.py
  gdsfactory/read/from_yaml.py
  gdsfactory/routing/add_electrical_pads_shortest.py
  gdsfactory/routing/add_electrical_pads_top.py
  gdsfactory/routing/add_electrical_pads_top_dc.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/auto_taper.py
  gdsfactory/routing/fanout2x2.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_bundle_all_angle.py
  gdsfactory/routing/route_bundle_sbend.py
  gdsfactory/routing/route_dubin.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/routing/route_ports_to_side.py
  gdsfactory/routing/route_quad.py
  gdsfactory/routing/route_sharp.py
  gdsfactory/routing/route_single.py
  gdsfactory/routing/route_single_from_steps.py
  gdsfactory/routing/route_single_sbend.py
  gdsfactory/routing/route_south.py
  gdsfactory/routing/sort_ports.py
  gdsfactory/routing/utils.py
  gdsfactory/routing/validation.py
  gdsfactory/schematic.py
  gdsfactory/typings.py
  gdsfactory/utils.py
  pyproject.toml
Labels: maintenance

#3466 Remove duplicate types
  gdsfactory/add_pins.py
  gdsfactory/component.py
  gdsfactory/components/crossing_waveguide.py
  gdsfactory/components/pad.py
  gdsfactory/cross_section.py
  gdsfactory/get_factories.py
  gdsfactory/pdk.py
  gdsfactory/port.py
  gdsfactory/routing/route_sharp.py
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_no_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_sc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_so_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_no_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_sc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_so_.yml
  gdsfactory/technology/layer_stack.py
  gdsfactory/typings.py
  tests/technology/test_layer_views.py
Labels: maintenance

#3467 deprecate d-attributes for path
  gdsfactory/component_layout.py
  gdsfactory/path.py
  notebooks/03_Path_CrossSection.ipynb
  notebooks/08_pdk.ipynb
  notebooks/09_pdk_import.ipynb
  notebooks/10_schematic.ipynb
  notebooks/11_best_practices.ipynb
  notebooks/_0_python.ipynb
Labels: maintenance

#3471 Layer stack accepts layers
  gdsfactory/technology/layer_stack.py
  tests/technology/test_layerstack.py
Labels: maintenance

#3473 Fix mypy errors in samples and components folders and cli file
  gdsfactory/cli.py
  gdsfactory/components/awg.py
  gdsfactory/components/coupler_broadband.py
  gdsfactory/components/crossing_waveguide.py
  gdsfactory/components/dbr_tapered.py
  gdsfactory/components/disk.py
  gdsfactory/components/grating_coupler_elliptical.py
  gdsfactory/components/grating_coupler_elliptical_arbitrary.py
  gdsfactory/components/grating_coupler_rectangular.py
  gdsfactory/components/grating_coupler_rectangular_arbitrary.py
  gdsfactory/components/taper.py
  gdsfactory/components/taper_adiabatic.py
  gdsfactory/components/via_corner.py
  gdsfactory/components/wire.py
  gdsfactory/cross_section.py
  gdsfactory/samples/03_move.py
  gdsfactory/samples/04_connect.py
  gdsfactory/samples/big_device.py
  gdsfactory/samples/big_device_electrical.py
  gdsfactory/samples/demo/lvs.py
  gdsfactory/samples/pdk/fab_c.py
  gdsfactory/samples/sample_reticle.py
  pyproject.toml
Labels: maintenance

#3475 Enforce layer in section
  gdsfactory/cross_section.py
  gdsfactory/generic_tech/layer_map.py
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_no_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_sc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_bend_euler_so_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_nc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_no_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_sc_.yml
  gdsfactory/samples/pdk/test_fab_c/test_settings_straight_so_.yml
Labels: maintenance

#3479 fix via_stack_with_offset
  .all-contributorsrc
  .gitpod.yml
  .libcst.codemod.yaml
  gdsfactory/components/vias/via_stack_with_offset.py
  test-data-regression/test_netlists_via_stack_with_offset_m1_m3_.yml
Labels: bug

#3480 Fix sections type
  gdsfactory/cross_section.py
  tests/test_paths_extrude.py
Labels: bug

#3483 Fix label side effect
  test-data-regression/test_import_json_label.yml
  tests/read/test_import_gds.py
Labels: bug

#3485 Eliminate side effects to global yaml behavior
  gdsfactory/technology/layer_views.py
  gdsfactory/technology/yaml_utils.py
Labels: bug

#3486 make netlist array instances nicer
  gdsfactory/get_netlist.py
  gdsfactory/read/from_yaml.py
  gdsfactory/schematic.py
  notebooks/10_yaml_component.ipynb
  notebooks/11_best_practices.ipynb
  test-data-regression/test_netlists_array_.yml
  test-data-regression/test_netlists_dbr_.yml
  test-data-regression/test_netlists_grating_coupler_dual_pol_.yml
  test-data-regression/test_netlists_pad_array0_.yml
  test-data-regression/test_netlists_pad_array180_.yml
  test-data-regression/test_netlists_pad_array270_.yml
  test-data-regression/test_netlists_pad_array90_.yml
  test-data-regression/test_netlists_pad_array_.yml
  test-data-regression/test_netlists_via_chain_.yml
  test-data-regression/test_netlists_via_stack_.yml
  test-data-regression/test_netlists_via_stack_heater_m2_.yml
  test-data-regression/test_netlists_via_stack_heater_m3_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_.yml
  test-data-regression/test_netlists_via_stack_m1_m3_.yml
  test-data-regression/test_netlists_via_stack_m1_mtop_.yml
  test-data-regression/test_netlists_via_stack_m2_m3_.yml
  test-data-regression/test_netlists_via_stack_npp_m1_.yml
  test-data-regression/test_netlists_via_stack_slab_m1_.yml
  test-data-regression/test_netlists_via_stack_slab_m1_horizontal_.yml
  test-data-regression/test_netlists_via_stack_slab_m2_.yml
  test-data-regression/test_netlists_via_stack_slab_m3_.yml
  test-data-regression/test_netlists_via_stack_slab_npp_m3_.yml
  test-data-regression/test_netlists_via_stack_with_offset_.yml
  test-data-regression/test_netlists_via_stack_with_offset_m1_m3_.yml
  test-data-regression/test_netlists_via_stack_with_offset_ppp_m1_.yml
  tests/read/test_component_from_yaml.py
  tests/test_get_netlist.py
Labels: enhancement

#3484 use pytest_randomly
  Makefile
  pyproject.toml
  uv.lock
Labels: maintenance

#3488 fixes bezier
  gdsfactory/components/__init__.py
  gdsfactory/components/bends/__init__.py
Labels: bug

#3489 mmi accepts component spec
  gdsfactory/components/mmis/mmi.py
Labels: maintenance

#3495 Add A* routing
  gdsfactory/port.py
  gdsfactory/routing/__init__.py
  gdsfactory/routing/route_astar.py
  gdsfactory/routing/route_single.py
  notebooks/04_routing.ipynb
Labels: enhancement

#3498 Better docs
  gdsfactory/component.py
  gdsfactory/components/texts/__init__.py
  gdsfactory/routing/route_single_from_steps.py
  notebooks/00_geometry.ipynb
  notebooks/01_references.ipynb
Labels: documentation

#3503 fix FileWatcher
  gdsfactory/cli.py
  gdsfactory/watch.py
Labels: bug

#3505 fix python3.10
  gdsfactory/component_layout.py
  gdsfactory/path.py
  gdsfactory/schematic.py
  pyproject.toml
  uv.lock
Labels: bug

#3506 Fix metal routing docstrings
  gdsfactory/boolean.py
  gdsfactory/components/shapes/triangles.py
  gdsfactory/components/superconductors/optimal_step.py
  gdsfactory/components/vias/via_stack_with_offset.py
  gdsfactory/components/waveguides/straight_heater_doped.py
  gdsfactory/grid.py
  gdsfactory/routing/add_electrical_pads_shortest.py
  gdsfactory/routing/add_electrical_pads_top.py
  gdsfactory/routing/add_electrical_pads_top_dc.py
  gdsfactory/routing/fanout2x2.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_quad.py
  gdsfactory/routing/route_sharp.py
  gdsfactory/routing/route_single.py
Labels: documentation

#3508 Add via circular pitch
  gdsfactory/components/vias/via.py
  test-data-regression/test_netlists_via_circular_.yml
  test-data-regression/test_settings_via_circular_.yml
Labels: bug

#3510 Remove terminated ports from gc array
  gdsfactory/components/grating_couplers/grating_coupler_array.py
  test-data-regression/test_netlists_die_with_pads_.yml
  test-data-regression/test_netlists_grating_coupler_array_.yml
Labels: bug

#3514 update kfactory
  gdsfactory/routing/route_single.py
  pyproject.toml
  test-data-regression/test_netlists_grating_coupler_array_.yml
  tests/routing/test_route_single_error.py
  uv.lock
Labels: dependencies

#3515 fix tests
  tests/components/test_netlists.py
Labels: bug

#3516 faster uv setup
  .github/workflows/test_code.yml
  Makefile
  tests/routing/test_route_ports_to_side.py
Labels: github_actions

#3519 fix samples and add tests for samples
  gdsfactory/samples/30_lidar.py
  gdsfactory/samples/30_lidar_pcell.py
  gdsfactory/samples/30_lidar_with_pads.py
  gdsfactory/samples/30_route_bundle_lidar.py
  gdsfactory/samples/33_route_bundle_nxn.py
  gdsfactory/samples/route_bundle_bbox2.py
  gdsfactory/samples/snap_bends.py
  gdsfactory/samples/snap_issue.py
  tests/test_samples.py
Labels: bug

#3521 fix awg
  .github/workflows/test_code.yml
  Makefile
  gdsfactory/components/__init__.py
  gdsfactory/components/filters/__init__.py
  gdsfactory/components/filters/awg.py
  pyproject.toml
  tests/components/test_netlists.py
  tests/routing/test_route_single_error.py
Labels: bug

#3522 add print for different packages
  gdsfactory/config.py
Labels: enhancement

#3526 Update bundle syntax within from_yaml parser
  gdsfactory/read/from_yaml.py
  gdsfactory/samples/netlists/mzi.yml
  gdsfactory/samples/netlists/straight_with_bend.yml
  gdsfactory/schematic.py
Labels: enhancement

#3524 Update taper_adiabatic.py
  gdsfactory/components/tapers/taper_adiabatic.py
  gdsfactory/path.py
  test-data-regression/test_netlists_taper_adiabatic_.yml
  test-data-regression/test_settings_taper_adiabatic_.yml
Labels: bug

#3530 update dependabot
  .github/dependabot.yml
  .github/workflows/pages.yml
  .github/workflows/test_code.yml
Labels: dependencies

#3532 fix duplicate ports
  docs/write_cells.py
  gdsfactory/component.py
Labels: bug

#3533 fix array_connect in YAML
  .github/workflows/test_code.yml
  .github/workflows/test_pdks.yml
  gdsfactory/read/from_yaml.py
  gdsfactory/samples/12_component_instance_arrays.py
  test-data-regression/test_gds_and_settings_sample_array_connect_reverse_.yml
  tests/read/test_component_from_yaml.py
Labels: bug

#3534 Fix to svg
  gdsfactory/export/to_svg.py
  tests/export/test_to_3d.py
  tests/export/test_to_stl.py
  tests/export/test_to_svg.py
Labels: bug

#3538 Feature/fix mypy errors
  Makefile
  gdsfactory/components/mzis/mzi_lattice.py
  gdsfactory/get_netlist.py
  gdsfactory/port.py
  gdsfactory/schematic.py
  gdsfactory/serialization.py
  gdsfactory/utils.py
  gdsfactory/watch.py
  tests/test_port.py
  tests/test_serialization.py
Labels: maintenance, code quaility

#3539 remove pytest_only dep
  pyproject.toml
  uv.lock
Labels: dependencies

#3541 fix gf version
  gdsfactory/cli.py
  gdsfactory/config.py
Labels: bug

#3540 Fix mypy errors
  gdsfactory/component.py
  gdsfactory/pdk.py
  gdsfactory/port.py
  test-data-regression/test_settings_wire_straight_.yml
Labels: maintenance, code quaility

#3543 remove import_gds cache
  gdsfactory/__init__.py
  gdsfactory/read/import_gds.py
Labels: bug

#3542 Fix mypy errors
  gdsfactory/component.py
  gdsfactory/component_layout.py
  gdsfactory/components/bends/bend_s.py
  gdsfactory/components/containers/extension.py
  gdsfactory/components/couplers/coupler.py
  gdsfactory/components/couplers/coupler_broadband.py
  gdsfactory/components/filters/awg.py
  gdsfactory/components/filters/mode_converter.py
  gdsfactory/components/grating_couplers/grating_coupler_elliptical_arbitrary.py
  gdsfactory/components/mzis/mzi.py
  gdsfactory/components/rings/ring.py
  gdsfactory/components/rings/ring_single_array.py
  gdsfactory/components/superconductors/optimal_hairpin.py
  gdsfactory/components/superconductors/optimal_step.py
  gdsfactory/components/superconductors/snspd.py
  gdsfactory/cross_section.py
  gdsfactory/difftest.py
  gdsfactory/export/to_gerber.py
  gdsfactory/functions.py
  gdsfactory/get_netlist.py
  gdsfactory/grid.py
  gdsfactory/labels/add_label_yaml.py
  gdsfactory/labels/ehva.py
  gdsfactory/pack.py
  gdsfactory/path.py
  gdsfactory/pdk.py
  gdsfactory/routing/route_astar.py
  gdsfactory/routing/route_bundle_all_angle.py
  gdsfactory/routing/route_ports_to_side.py
  gdsfactory/snap.py
  gdsfactory/typings.py
  pyproject.toml
  tests/read/test_updk.py
Labels: maintenance

#3544 Fix ALL mypy errors!
  .github/workflows/test_code.yml
  gdsfactory/add_pins.py
  gdsfactory/component.py
  gdsfactory/component_layout.py
  gdsfactory/components/pcms/cutback_bend.py
  gdsfactory/components/pcms/cutback_loss.py
  gdsfactory/components/rings/ring.py
  gdsfactory/components/rings/ring_pn.py
  gdsfactory/components/shapes/rectangle.py
  gdsfactory/components/tapers/taper_adiabatic.py
  gdsfactory/components/waveguides/straight_heater_doped.py
  gdsfactory/components/waveguides/straight_heater_meander_doped.py
  gdsfactory/cross_section.py
  gdsfactory/font.py
  gdsfactory/functions.py
  gdsfactory/get_netlist.py
  gdsfactory/path.py
  gdsfactory/pdk.py
  gdsfactory/port.py
  gdsfactory/read/from_yaml.py
  gdsfactory/routing/route_astar.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_quad.py
  gdsfactory/routing/utils.py
  gdsfactory/technology/layer_stack.py
  pyproject.toml
Labels: maintenance

#3547 Fix route ports to side kwargs
  docs/api_routing.rst
  gdsfactory/routing/__init__.py
  gdsfactory/routing/route_ports_to_side.py
Labels: bug

#3549 Fix is_cell
  gdsfactory/get_factories.py
  tests/test_get_factories.py
Labels: bug

#3551 add straight_piecewise
  gdsfactory/components/__init__.py
  gdsfactory/components/waveguides/__init__.py
  gdsfactory/components/waveguides/straight_piecewise.py
  tests/components/test_components.py
  tests/components/test_netlists.py
Labels: enhancement

#3557 fix freetype
  gdsfactory/font.py
Labels: bug

#3550 Add more tests
  .coveragerc
  gdsfactory/__init__.py
  gdsfactory/_cell.py
  gdsfactory/add_padding.py
  gdsfactory/components/containers/array_component.py
  gdsfactory/functions.py
  gdsfactory/technology/layer_views.py
  gdsfactory/technology/xml_utils.py
  gdsfactory/typings.py
  gdsfactory/utils.py
  gdsfactory/watch.py
  tests/components/bends/__init__.py
  tests/components/bends/test_bend_circular_heater.py
  tests/components/containers/__init__.py
  tests/components/containers/test_array_component.py
  tests/components/containers/test_extend_ports_list.py
  tests/components/couplers/__init__.py
  tests/components/couplers/test_coupler.py
  tests/technology/test_layer_views.py
  tests/technology/test_xml_utils.py
  tests/technology/test_yaml_utils.py
  tests/test_add_padding.py
  tests/test_add_pins.py
  tests/test_watch.py
  tests/test_write_cells.py
  uv.lock
Labels: enhancement, code quaility

#3558 Remove deprecated methods from tests
  Makefile
  gdsfactory/components/grating_couplers/functions.py
  gdsfactory/components/mzis/mzi_pads_center.py
  gdsfactory/components/pads/pad_gsg.py
  gdsfactory/components/pcms/cutback_bend.py
  gdsfactory/components/waveguides/straight_heater_meander_doped.py
  gdsfactory/functions.py
  gdsfactory/generic_tech/simulation_settings.py
  gdsfactory/pdk.py
  gdsfactory/read/from_yaml.py
  gdsfactory/read/from_yaml_template.py
  gdsfactory/schematic.py
  gdsfactory/technology/layer_views.py
  gdsfactory/technology/xml_utils.py
  pyproject.toml
  test-data-regression/test_netlists_mzi_pads_center_.yml
  test-data-regression/test_netlists_pad_gsg_open_.yml
  test-data-regression/test_netlists_pad_gsg_short_.yml
  test-data-regression/test_netlists_straight_heater_meander_doped_.yml
  test-data-regression/test_settings_straight_heater_meander_doped_.yml
  tests/components/containers/test_array_component.py
  tests/components/test_components.py
  tests/components/test_netlists.py
  tests/read/test_component_from_yaml.py
  tests/read/test_import_gds.py
  tests/read/test_updk.py
  tests/technology/test_layer_views.py
  tests/test_get_netlist.py
Labels: maintenance

#3559 Add more tests
  .coveragerc
  Makefile
  gdsfactory/add_pins.py
  gdsfactory/port.py
  gdsfactory/routing/route_south.py
  gdsfactory/routing/sort_ports.py
  gdsfactory/routing/validation.py
  gdsfactory/technology/klayout_tech.py
  gdsfactory/technology/layer_views.py
  gdsfactory/watch.py
  tests/export/test_to_svg.py
  tests/routing/test_route_single_from_steps.py
  tests/routing/test_route_single_sbend.py
  tests/routing/test_route_south.py
  tests/routing/test_sort_ports.py
  tests/routing/test_utils.py
  tests/routing/test_validation.py
  tests/technology/test_color_utils.py
  tests/technology/test_klayout_tech.py
  tests/technology/test_layer_map.py
  tests/technology/test_layer_views.py
  tests/technology/test_xml_utils.py
  tests/test_add_pins.py
  tests/test_watch.py
Labels: enhancement

#3562 add angle resolution to via_circular
  gdsfactory/components/vias/via.py
  test-data-regression/test_netlists_via_circular_.yml
  test-data-regression/test_settings_via_circular_.yml
Labels: maintenance

#3563 Simpler straight heater meander default args
  gdsfactory/components/waveguides/straight_heater_meander.py
  gdsfactory/components/waveguides/straight_heater_metal.py
  test-data-regression/test_netlists_mzi2x2_2x2_phase_shifter_.yml
  test-data-regression/test_netlists_mzi_phase_shifter_.yml
  test-data-regression/test_netlists_mzi_phase_shifter_top_heater_metal_.yml
  test-data-regression/test_netlists_straight_heater_meander_.yml
  test-data-regression/test_settings_add_pads0_.yml
  test-data-regression/test_settings_straight_heater_meander_.yml
  test-data-regression/test_settings_straight_heater_metal_.yml
  test-data-regression/test_settings_straight_heater_metal_90_90_.yml
  test-data-regression/test_settings_straight_heater_metal_simple_.yml
  test-data-regression/test_settings_straight_heater_metal_undercut_.yml
  test-data-regression/test_settings_straight_heater_metal_undercut_90_90_.yml
Labels: maintenance
