Repository gdsfactory/gdsfactory, pull requests merged in 2025-01, with the labels that each got.

#3565 ensure GDSDIR_TEMP exists
  gdsfactory/config.py
Labels: bug

#3567 fix cutbacks
  gdsfactory/components/containers/component_sequence.py
  gdsfactory/components/pcms/cutback_loss.py
Labels: bug

#3566 fixing docs for non-orthogonal grid array
  gdsfactory/schematic.py
Labels: bug

#3569 add filepath to yaml cell
  gdsfactory/read/from_yaml_template.py
Labels: enhancement

#3573 Fix ring pn v2
  gdsfactory/components/filters/dbr_tapered.py
  gdsfactory/components/rings/ring_pn.py
  gdsfactory/samples/03_move.py
  test-data-regression/test_netlists_dbr_tapered_.yml
  test-data-regression/test_netlists_ring_double_pn_.yml
  test-data-regression/test_netlists_ring_single_pn_.yml
  test-data-regression/test_settings_ring_single_pn_.yml
  uv.lock
Labels: bug

#3572 register containers in pdk
  gdsfactory/generic_tech/__init__.py
  gdsfactory/pdk.py
  gdsfactory/read/from_yaml.py
  tests/read/test_component_from_yaml.py
Labels: enhancement

#3575 Clean connectivity for some components
  gdsfactory/components/couplers/coupler.py
  gdsfactory/components/couplers/coupler_full.py
  gdsfactory/components/dies/seal_ring.py
  gdsfactory/components/pcms/cdsem_coupler.py
  gdsfactory/components/pcms/cdsem_straight.py
  gdsfactory/components/pcms/cdsem_straight_density.py
  gdsfactory/components/pcms/litho_calipers.py
  gdsfactory/components/pcms/verniers.py
  gdsfactory/components/rings/ring_heater.py
  gdsfactory/components/spirals/delay_snake_sbend.py
  gdsfactory/components/superconductors/snspd.py
  gdsfactory/components/tapers/taper.py
  gdsfactory/components/vias/via_stack.py
  gdsfactory/components/waveguides/straight.py
  gdsfactory/components/waveguides/straight_heater_metal.py
  gdsfactory/components/waveguides/wire.py
  gdsfactory/cross_section.py
  gdsfactory/path.py
  gdsfactory/pdk.py
  test-data-regression/test_netlists_cdsem_coupler_.yml
  test-data-regression/test_netlists_cdsem_straight_.yml
  test-data-regression/test_netlists_cdsem_straight_density_.yml
  test-data-regression/test_netlists_delay_snake_sbend_.yml
  test-data-regression/test_netlists_litho_calipers_.yml
  test-data-regression/test_netlists_pad_array0_.yml
  test-data-regression/test_netlists_pad_array180_.yml
  test-data-regression/test_netlists_pad_array270_.yml
  test-data-regression/test_netlists_pad_array90_.yml
  test-data-regression/test_netlists_pad_array_.yml
  test-data-regression/test_netlists_ring_double_heater_.yml
  test-data-regression/test_netlists_ring_single_heater_.yml
  test-data-regression/test_netlists_seal_ring_.yml
  test-data-regression/test_netlists_snspd_.yml
  test-data-regression/test_netlists_verniers_.yml
  test-data-regression/test_netlists_wire_corner_.yml
  test-data-regression/test_settings_cdsem_coupler_.yml
  test-data-regression/test_settings_cdsem_straight_.yml
  test-data-regression/test_settings_cdsem_straight_density_.yml
  test-data-regression/test_settings_delay_snake_sbend_.yml
  test-data-regression/test_settings_verniers_.yml
  test-data-regression/test_settings_wire_corner_.yml
  tests/components/test_netlists.py
Labels: bug

#3578 improve_add_electrical_pads_shortest
  gdsfactory/routing/add_electrical_pads_shortest.py
Labels: maintenance

#3581 only define straight and bend in route_bundle if necessary
  gdsfactory/routing/route_bundle.py
Labels: bug

#3582 fix grating_coupler_tree
  gdsfactory/components/grating_couplers/grating_coupler_tree.py
  test-data-regression/test_netlists_grating_coupler_tree_.yml
  test-data-regression/test_settings_grating_coupler_tree_.yml
Labels: bug, maintenance

#3585 expose sbend
  gdsfactory/components/couplers/coupler.py
  test-data-regression/test_netlists_cavity_.yml
  test-data-regression/test_netlists_coupler_.yml
  test-data-regression/test_netlists_mzi_coupler_.yml
  test-data-regression/test_netlists_mzi_lattice_.yml
  test-data-regression/test_netlists_mzit_.yml
  test-data-regression/test_netlists_ring_crow_couplers_.yml
  test-data-regression/test_settings_coupler_.yml
Labels: maintenance

#3586 remove unused param
  gdsfactory/read/import_gds.py
Labels: maintenance

#3574 update to kfactory 0.23.0
  Makefile
  gdsfactory/component.py
  gdsfactory/components/containers/pack_doe.py
  gdsfactory/components/mmis/mmi2x2_with_sbend.py
  gdsfactory/cross_section.py
  gdsfactory/export/to_svg.py
  gdsfactory/samples/snap_bends_fixed.py
  gdsfactory/samples/snap_issue.py
  notebooks/01_references.ipynb
  pyproject.toml
  test-data-regression/test_netlists_text_rectangular_multi_layer_.yml
  tests/read/test_component_from_yaml.py
  uv.lock
Labels: enhancement, help wanted

#3589 update kfactory to 0.23.1
  pyproject.toml
  uv.lock
Labels: dependencies

#3591 fixes ComponentAllAngle copy
  gdsfactory/component.py
Labels: bug

#3594 regenerate uv.lock
  gdsfactory/utils.py
  uv.lock
Labels: bug, dependencies

#3590 swap_inheritance_order
  gdsfactory/add_pins.py
  gdsfactory/component.py
  tests/routing/test_route_single_sbend.py
Labels: bug

#3596 Move Component only functions to Component class
  gdsfactory/component.py
  gdsfactory/functions.py
Labels: bug

#3601 update pydantic min version
  pyproject.toml
  uv.lock
Labels: dependencies

#3600 fix extend ports
  gdsfactory/component.py
  gdsfactory/components/containers/extension.py
  test-data-regression/test_netlists_extend_ports_.yml
  tests/components/test_composed_functions.py
Labels: bug

#3602 Fix wrong Component.copy
  gdsfactory/component.py
  test-data-regression/test_netlists_text_rectangular_multi_layer_.yml
  tests/test_component.py
Labels: bug

#3604 Update taper_cross_section.py
  gdsfactory/components/tapers/taper_cross_section.py
Labels: bug

#3606 document_changing_dbu
  notebooks/12_grid_snapping.ipynb
Labels: documentation

#3598 Add more ComponentAllAngle tests
  gdsfactory/component.py
  gdsfactory/functions.py
  tests/test_component.py
Labels: enhancement

#3612 fix grid rotation
  gdsfactory/grid.py
Labels: bug

#3614 Add more tests
  Makefile
  gdsfactory/components/bends/bend_circular.py
  gdsfactory/components/bends/bend_euler.py
  gdsfactory/components/containers/component_sequence.py
  gdsfactory/components/containers/extension.py
  gdsfactory/export/to_np.py
  tests/components/bends/test_bend_circular_heater.py
  tests/components/bends/test_bends.py
  tests/components/containers/test_add_fiber_array_optical_south_electrical_north.py
  tests/components/containers/test_add_termination.py
  tests/components/containers/test_array_component.py
  tests/components/containers/test_component_sequence.py
  tests/components/containers/test_extension.py
  tests/components/containers/test_pack_doe.py
  tests/components/test_components.py.disable
  tests/components/test_components_serialize.py.disable
  tests/export/test_to_np.py
Labels: enhancement

#3620 add tests for containers
  gdsfactory/components/containers/add_fiber_array_optical_south_electrical_north.py
  gdsfactory/components/containers/pack_doe.py
  gdsfactory/components/shapes/bbox.py
  gdsfactory/samples/sample_reticle.py
  gdsfactory/samples/sample_reticle_with_labels.py
  notebooks/07_mask.ipynb
  test-data-regression/test_settings_add_fiber_array_optical_south_electrical_north_.yml
  test-data-regression/test_settings_bbox_.yml
  test-data-regression/test_settings_pack_doe_.yml
  test-data-regression/test_settings_pack_doe_grid_.yml
  tests/components/test_components.py
  tests/test_component.py
Labels: enhancement, maintenance

#3622 fix gf.boolean for arrays
  gdsfactory/boolean.py
  tests/test_boolean.py
Labels: bug

#3623 Underscore intermediate functions
  gdsfactory/components/pcms/cutback_2x2.py
  gdsfactory/components/rings/ring_pn.py
Labels: maintenance

#3625 update kfactory
  pyproject.toml
  uv.lock
Labels: dependencies

#3624 remove default 1,0 boolean layer
  gdsfactory/boolean.py
  gdsfactory/font.py
  notebooks/04_components_geometry.ipynb
  tests/test_boolean.py
Labels: maintenance

#3626 improve pack error message
  gdsfactory/pack.py
Labels: documentation

#3627 add remove_old_layer_flag to over_under
  gdsfactory/component.py
  tests/test_boolean.py
Labels: enhancement, maintenance

#3629 Fix mypy issue
  gdsfactory/pack.py
Labels: bug

#3635 remove zero length waveguides from cutback_component
  gdsfactory/components/pcms/cutback_component.py
Labels: bug

#3636 cleanup_precommit
  .pre-commit-config.yaml
Labels: maintenance

#3638 fix cutback_component
  gdsfactory/components/pcms/cutback_component.py
  uv.lock
Labels: bug
