Repository gdsfactory/gdsfactory, pull requests merged in 2025-04, with the labels that each got.

#3755 Expose insets and add_ports_top
  gdsfactory/cross_section.py
  gdsfactory/routing/add_pads.py
Labels: maintenance

#3756 allow_none_radius
  gdsfactory/components/bends/bend_s.py
Labels: maintenance

#3759 fix mypy
  gdsfactory/components/spirals/spiral_heater.py
  gdsfactory/components/waveguides/straight_heater_meander_doped.py
  gdsfactory/routing/route_single.py
Labels: bug

#3762 avoid double pdk activation
  CHANGELOG.md
  gdsfactory/pdk.py
  tests/components/test_components.py
Labels: documentation

#3766 fix tests
  gdsfactory/components/waveguides/straight_heater_doped.py
Labels: bug

#3768 fix self-intersecting path
  gdsfactory/path.py
  tests/test_path.py
Labels: bug

#3772 fix path rotate
  CHANGELOG.md
  gdsfactory/path.py
  tests/test_path.py
Labels: bug, documentation

#3773 move mypy to cicd
  .github/workflows/test_code.yml
  .pre-commit-config.yaml
  Makefile
  gdsfactory/cli.py
  gdsfactory/component.py
  gdsfactory/export/to_3d.py
  gdsfactory/generic_tech/klayout/python/kgdsfactory/__init__.py
  gdsfactory/pdk.py
  gdsfactory/serialization.py
  gdsfactory/technology/yaml_utils.py
  pyproject.toml
Labels: maintenance

#3774 add Stargazers
  README.md
Labels: documentation, enhancement

#3777 Fix text rectangular
  gdsfactory/components/texts/text_rectangular.py
Labels: bug

#3782 enable sbend routing in schematic
  gdsfactory/pdk.py
  gdsfactory/routing/factories.py
  gdsfactory/routing/route_bundle_sbend.py
  pyproject.toml
Labels: enhancement

#3785 better error message
  gdsfactory/read/from_yaml.py
  pyproject.toml
Labels: documentation

#3788 Improve sbend metal
  gdsfactory/components/waveguides/wire.py
  gdsfactory/export/to_3d.py
  gdsfactory/pack.py
  gdsfactory/routing/route_bundle_sbend.py
  tests/routing/test_routing_route_bundle_sbend.py
Labels: bug

#3791 bump kfactory to 1.5
  pyproject.toml
Labels: dependencies

#3793 Add codeowners file
  .github/CODEOWNERS
Labels: enhancement

#3792 Fix typing for cell_with_module_name
  gdsfactory/_cell.py
Labels: bug

#3797 Fix get netlist
  gdsfactory/components/rings/ring_single.py
  gdsfactory/get_netlist.py
Labels: bug

#3799 remove lost plot
  gdsfactory/read/from_yaml.py
Labels: bug

#3800 Add warning stacklevels
  gdsfactory/__init__.py
  gdsfactory/add_pins.py
  gdsfactory/add_ports.py
  gdsfactory/component.py
  gdsfactory/components/bends/bend_circular.py
  gdsfactory/components/bends/bend_euler.py
  gdsfactory/components/texts/text_freetype.py
  gdsfactory/cross_section.py
  gdsfactory/functions.py
  gdsfactory/get_netlist.py
  gdsfactory/pdk.py
  gdsfactory/port.py
  gdsfactory/read/from_updk.py
  gdsfactory/read/from_yaml.py
  gdsfactory/routing/auto_taper.py
  gdsfactory/routing/validation.py
  gdsfactory/snap.py
  gdsfactory/technology/layer_views.py
  pyproject.toml
Labels: enhancement

#3801 bump kfactory to 1.5.2 at least
  pyproject.toml
Labels: dependencies

#3802 pin klayout==0.30.0
  pyproject.toml
Labels: dependencies
