Repository gdsfactory/gdsfactory, pull requests merged in 2025-08, with the labels that each got.

#4069 fix tests
  tests/components/test_components.py
Labels: bug

#4070 Skip diffing on same file instead of crashing
  gdsfactory/difftest.py
Labels: bug

#4072 Better message errors
  README.md
  docs/developer.md
  gdsfactory/components/couplers/coupler.py
  gdsfactory/components/couplers/coupler_ring.py
  gdsfactory/components/grating_couplers/grating_coupler_array.py
  gdsfactory/components/rings/ring_double.py
  gdsfactory/components/rings/ring_heater.py
  gdsfactory/components/rings/ring_single.py
  gdsfactory/components/rings/ring_single_bend_coupler.py
  gdsfactory/components/rings/ring_single_dut.py
  gdsfactory/generic_tech/__init__.py
  gdsfactory/pdk.py
  gdsfactory/port.py
  gdsfactory/routing/add_fiber_array.py
  gdsfactory/routing/add_fiber_single.py
  notebooks/04_components_geometry.ipynb
  notebooks/_0_python.ipynb
  test-data-regression/test_netlists_coupler_ring_.yml
  test-data-regression/test_netlists_coupler_symmetric_.yml
  test-data-regression/test_netlists_die_with_pads_.yml
  test-data-regression/test_netlists_ring_double_.yml
  test-data-regression/test_netlists_ring_double_heater_.yml
  test-data-regression/test_netlists_ring_single_.yml
  test-data-regression/test_netlists_ring_single_array_.yml
  test-data-regression/test_netlists_ring_single_dut_.yml
  test-data-regression/test_netlists_ring_single_heater_.yml
  test-data-regression/test_settings_coupler_bend_.yml
  test-data-regression/test_settings_coupler_ring_.yml
  test-data-regression/test_settings_coupler_ring_bend_.yml
  test-data-regression/test_settings_coupler_symmetric_.yml
  test-data-regression/test_settings_grating_coupler_array_.yml
  test-data-regression/test_settings_ring_double_.yml
  test-data-regression/test_settings_ring_double_heater_.yml
  test-data-regression/test_settings_ring_single_.yml
  test-data-regression/test_settings_ring_single_dut_.yml
  test-data-regression/test_settings_ring_single_heater_.yml
  tests/test_component.py
Labels: documentation, enhancement

#4073 Simpler fill
  README.md
  gdsfactory/component.py
  gdsfactory/pdk.py
  notebooks/04_components_geometry.ipynb
Labels: documentation, enhancement

#4074 simpler layer info check
  gdsfactory/pdk.py
Labels: maintenance

#4077 bump kfactory to 1.12.1
  pyproject.toml
Labels: dependencies

#4075 skip_duplicate_labels
  gdsfactory/add_ports.py
Labels: maintenance

#4080 Allow to flatten on copy_layers
  gdsfactory/components/containers/copy_layers.py
  test-data-regression/test_netlists_copy_layers_.yml
  test-data-regression/test_settings_copy_layers_.yml
Labels: maintenance

#4084 bump kf to 0.12.2
  pyproject.toml
Labels: dependencies

#4092 update kfactory to 1.12.3
  pyproject.toml
Labels: documentation

#4089 Using TypedDict instead of dataclass for Step
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/routing/route_single.py
  gdsfactory/typings.py
Labels: maintenance

#4094 add more tests
  tests/test_component.py
Labels: enhancement

#4090 Inferring port type for the cross section in route functions
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_single.py
  test-data-regression/test_netlists_edge_coupler_array_with_loopback_.yml
  test-data-regression/test_netlists_grating_coupler_loss_.yml
  test-data-regression/test_netlists_splitter_tree_.yml
  test-data-regression/test_netlists_switch_tree_.yml
Labels: routing, maintenance

#4104 Extend optional parameters for lyp_to_dataclass
  gdsfactory/technology/layer_map.py
Labels: maintenance

#4115 Undoing hardcoded max_cellname_length=32 (pull from CONF)
  gdsfactory/difftest.py
Labels: bug

#4108 Remove convert_tuples_to_lists in favor of yaml.safe_dump
  gdsfactory/add_pins.py
  gdsfactory/component.py
  gdsfactory/labels/add_label_yaml.py
  gdsfactory/pdk.py
  gdsfactory/read/from_updk.py
  gdsfactory/schematic.py
  gdsfactory/serialization.py
  notebooks/10_schematic.ipynb
  tests/test_serialization.py
Labels: maintenance

#4119 add raise_on_error flag and expand to electrical
  gdsfactory/routing/route_bundle.py
Labels: maintenance

#4120 Fix cross-section default naming (particularly for PDKs)
  gdsfactory/cross_section.py
  gdsfactory/pdk.py
Labels: maintenance

#4123 Simplify and fix the condition checks on path extrusion
  gdsfactory/path.py
Labels: maintenance

#4124 Skip angle calculation with single point in path
  gdsfactory/path.py
Labels: maintenance

#4125 Allow passing angular step to arc/bend_arc
  gdsfactory/components/bends/bend_circular.py
  gdsfactory/path.py
  test-data-regression/test_netlists_bend_circular180_.yml
  test-data-regression/test_netlists_bend_circular_.yml
  test-data-regression/test_netlists_coupler90circular_.yml
  test-data-regression/test_netlists_cutback_bend90circular_.yml
  test-data-regression/test_netlists_ring_asymmetric_.yml
  test-data-regression/test_netlists_ring_crow_couplers_.yml
  test-data-regression/test_settings_bend_circular180_.yml
  test-data-regression/test_settings_bend_circular_.yml
  test-data-regression/test_settings_bend_circular_all_angle_.yml
Labels: maintenance

#4140 Update pre-commit
  .pre-commit-config.yaml
Labels: maintenance

#4129 enfore types in constants
  gdsfactory/__init__.py
  gdsfactory/generic_tech/__init__.py
  gdsfactory/pdk.py
  notebooks/08_pdk.ipynb
Labels: enhancement

#4142 more configurable fanout2x2 with better defaults
  gdsfactory/routing/fanout2x2.py
Labels: maintenance
