Repository gdsfactory/gdsfactory, pull requests merged in 2025-05, with the labels that each got.

#3805 better readme
  README.md
Labels: documentation

#3804 use cross_section in route_bundle for electrical cases
  gdsfactory/routing/route_bundle.py
  pyproject.toml
Labels: bug

#3807 Add `auto_taper_pads` flag to route_fiber_array_pads_north
  docs/developer.md
  gdsfactory/components/containers/add_fiber_array_optical_south_electrical_north.py
  test-data-regression/test_settings_add_fiber_array_optical_south_electrical_north_.yml
Labels: documentation, maintenance

#3815 fix route_single
  gdsfactory/components/grating_couplers/grating_coupler_array.py
  gdsfactory/routing/route_single.py
Labels: bug

#3817 improve migration docs
  notebooks/21_migration_guide_7_8.ipynb
Labels: documentation

#3818 make grating_coupler optional in die_with_pads
  gdsfactory/components/dies/die_with_pads.py
Labels: maintenance

#3819 gc array bend
  gdsfactory/components/grating_couplers/grating_coupler_array.py
Labels: bug

#3821 improve docs
  notebooks/00_geometry.ipynb
Labels: documentation

#3822 prevent container conflicts
  gdsfactory/generic_tech/__init__.py
  gdsfactory/pdk.py
  tests/test_pdk.py
Labels: bug

#3823 fix docs
  notebooks/07_mask.ipynb
Labels: bug

#3824 remove add_padding default
  gdsfactory/add_padding.py
Labels: documentation

#3825 add codeflash
  .github/workflows/codeflash.yaml
  pyproject.toml
Labels: enhancement

#3843 Fix tests
  .github/workflows/codeflash.yaml
  gdsfactory/components/containers/extension.py
  tests/test_watch.py
Labels: bug

#3844 add codeflash as a dev dep
  pyproject.toml
Labels: enhancement

#3845 update contributors
  README.md
Labels: documentation

#3852 add codeflash label
  .github/release-drafter.yml
Labels: enhancement

#3854 fix pre-commit
  gdsfactory/get_factories.py
Labels: bug

#3861 Run ty in ci
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test_code.yml
  gdsfactory/read/from_yaml.py
  gdsfactory/technology/yaml_utils.py
  pyproject.toml
Labels: typing

#3859 bump kfactory
  pyproject.toml
  test-data-regression/test_netlists_add_termination_.yml
  test-data-regression/test_netlists_awg_.yml
  test-data-regression/test_netlists_bend_euler_s_.yml
  test-data-regression/test_netlists_cavity_.yml
  test-data-regression/test_netlists_coupler_broadband_.yml
  test-data-regression/test_netlists_coupler_symmetric_.yml
  test-data-regression/test_netlists_delay_snake_sbend_.yml
  test-data-regression/test_netlists_die_with_pads_.yml
  test-data-regression/test_netlists_edge_coupler_array_with_loopback_.yml
  test-data-regression/test_netlists_extend_ports_.yml
  test-data-regression/test_netlists_grating_coupler_dual_pol_.yml
  test-data-regression/test_netlists_grating_coupler_loss_.yml
  test-data-regression/test_netlists_grating_coupler_tree_.yml
  test-data-regression/test_netlists_litho_steps_.yml
  test-data-regression/test_netlists_loop_mirror_.yml
  test-data-regression/test_netlists_mode_converter_.yml
  test-data-regression/test_netlists_mzit_.yml
  test-data-regression/test_netlists_ring_double_.yml
  test-data-regression/test_netlists_ring_single_.yml
  test-data-regression/test_netlists_ring_single_dut_.yml
  test-data-regression/test_netlists_spiral_.yml
  test-data-regression/test_netlists_spiral_racetrack_heater_doped_.yml
  test-data-regression/test_netlists_splitter_tree_.yml
  test-data-regression/test_netlists_straight_pin_.yml
  test-data-regression/test_netlists_straight_pin_slot_.yml
  test-data-regression/test_netlists_straight_pn_.yml
  test-data-regression/test_netlists_straight_pn_slot_.yml
  test-data-regression/test_netlists_switch_tree_.yml
  test-data-regression/test_netlists_triangle2_.yml
  test-data-regression/test_netlists_triangle2_thin_.yml
  test-data-regression/test_netlists_triangle4_.yml
  test-data-regression/test_netlists_triangle4_thin_.yml
  test-data-regression/test_netlists_via_stack_corner45_extended_.yml
Labels: dependencies

#3875 ⚡️ Speed up function `add_auto_tapers` by 39%
  gdsfactory/routing/auto_taper.py
Labels: maintenance, code quaility

#3874 Improve docs
  .gitignore
  README.md
  gdsfactory/components/analog/interdigital_capacitor.py
  gdsfactory/components/superconductors/hline.py
Labels: documentation

#3897 fix pre-commit
  gdsfactory/components/rings/ring_single.py
  gdsfactory/components/spirals/spiral_inductor.py
  gdsfactory/get_factories.py
Labels: bug, maintenance

#3900 Refactor PDK xsection decorator
  gdsfactory/pdk.py
Labels: maintenance

#3898 Improve function signatures
  gdsfactory/get_factories.py
Labels: maintenance

#3899 draft: Improve contribution doc
  .gitignore
  docs/contribution.md
Labels: maintenance

#3901 Update python intro docs
  Makefile
  notebooks/_0_python.ipynb
Labels: documentation

#3902 lint(pre-commit-config): update ruff version to v0.11.10
  .pre-commit-config.yaml
Labels: github_actions

#3903 fix pre-commit
  gdsfactory/components/grating_couplers/functions.py
Labels: bug

#3904 Fix pytest warnings
  gdsfactory/components/tapers/taper_adiabatic.py
  gdsfactory/read/from_yaml.py
  gdsfactory/technology/layer_views.py
Labels: github_actions, code quaility

#3918 Update makefile documentation
  .github/workflows/test_code.yml
  .vscode/settings.json
  Makefile
Labels: maintenance

#3921 better docstrings
  gdsfactory/components/texts/text.py
  gdsfactory/components/texts/text_rectangular.py
  gdsfactory/components/waveguides/straight.py
  gdsfactory/cross_section.py
  gdsfactory/routing/validation.py
Labels: documentation

#3941 rename length info coupler
  gdsfactory/components/couplers/coupler.py
Labels: maintenance

#3945 register all angle components in pdk
  gdsfactory/get_factories.py
  gdsfactory/routing/route_bundle_all_angle.py
  gdsfactory/typings.py
  test-data-regression/test_route_bundle_all_angle.yml
  test-data-regression/test_settings_bend_circular_all_angle_.yml
  test-data-regression/test_settings_bend_euler_all_angle_.yml
  test-data-regression/test_settings_straight_all_angle_.yml
  tests/components/test_netlists.py
Labels: enhancement, minor

#3946 Add get_cell overload
  gdsfactory/pdk.py
  gdsfactory/routing/route_bundle_all_angle.py
  gdsfactory/typings.py
Labels: bug, enhancement

#3949 add lvs equivalent port option
  gdsfactory/_cell.py
  pyproject.toml
Labels: enhancement

#3950 Widen Component function arguments
  gdsfactory/component.py
Labels: typing
