Repository gdsfactory/gdsfactory, pull requests merged in 2025-02, with the labels that each got.

#3643 Fix nitride transition
  gdsfactory/component.py
  gdsfactory/components/tapers/taper.py
  gdsfactory/functions.py
  test-data-regression/test_netlists_taper_nc_sc_.yml
  test-data-regression/test_settings_taper_nc_sc_.yml
  tests/test_component.py
Labels: bug

#3644 flatten_nitride_transition
  gdsfactory/components/tapers/taper.py
  test-data-regression/test_netlists_taper_nc_sc_.yml
Labels: maintenance

#3647 making auto tapering reflexive
  gdsfactory/routing/auto_taper.py
  tests/routing/test_auto_taper.py
Labels: enhancement

#3648 Small improvements
  gdsfactory/routing/route_single_sbend.py
  gdsfactory/technology/layer_stack.py
Labels: maintenance

#3649 fix type annotations
  gdsfactory/routing/route_single_sbend.py
Labels: bug, maintenance

#3650 solid dither pattern does not exist
  gdsfactory/technology/layer_views.py
Labels: bug

#3652 better instance validation errors
  gdsfactory/schematic.py
Labels: enhancement

#3653 fix a lot of routing bugs
  gdsfactory/routing/route_bundle.py
Labels: bug

#3657 Support via stack different xy offsets
  gdsfactory/components/vias/via_stack.py
Labels: maintenance

#3659 Fix routing
  gdsfactory/cross_section.py
  gdsfactory/port.py
  gdsfactory/routing/add_pads.py
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_fiber_array.py
Labels: bug

#3665 Fix circular imports
  gdsfactory/component.py
  gdsfactory/components/grating_couplers/grating_coupler_array.py
  gdsfactory/components/grating_couplers/grating_coupler_elliptical_lumerical.py
  gdsfactory/cross_section.py
  gdsfactory/port.py
  gdsfactory/routing/auto_taper.py
  gdsfactory/routing/route_fiber_array.py
  gdsfactory/samples/12_component_refs.py
  gdsfactory/samples/34_route_edge_coupler_bend_s.py
  gdsfactory/samples/demo/lvs.py
  gdsfactory/samples/pdk/fab_d/phase_shifters.py
  gdsfactory/typings.py
  gdsfactory/watch.py
Labels: bug

#3666 Fix grating coupler loss
  README.md
  gdsfactory/components/grating_couplers/grating_coupler_loss.py
  test-data-regression/test_netlists_grating_coupler_loss_.yml
  test-data-regression/test_settings_grating_coupler_loss_.yml
Labels: bug, documentation

#3673 add warning for python3.10
  gdsfactory/__init__.py
Labels: maintenance

#3674 improve migration guides
  README.md
  notebooks/21_migration_guide_7_8.ipynb
  notebooks/22_migration_8.ipynb
Labels: documentation

#3678 allow zero length coupling rings
  gdsfactory/components/rings/ring_single.py
Labels: maintenance

#3676 Add more tests and change inheritance of Path
  .github/workflows/test_code.yml
  Makefile
  gdsfactory/component_layout.py
  gdsfactory/path.py
  gdsfactory/pdk.py
  notebooks/03_Path_CrossSection.ipynb
  tests/test_path.py
Labels: enhancement

#3680 Add more tests
  gdsfactory/__init__.py
  gdsfactory/add_ports.py
  gdsfactory/component.py
  gdsfactory/components/bends/bend_s.py
  gdsfactory/components/containers/component_sequence.py
  gdsfactory/components/containers/pack_doe.py
  gdsfactory/functions.py
  gdsfactory/get_netlist.py
  gdsfactory/pack.py
  tests/components/bends/test_bends.py
  tests/components/containers/test_component_sequence.py
  tests/components/containers/test_extension.py
  tests/components/containers/test_pack_doe.py
  tests/components/couplers/test_coupler.py
  tests/components/couplers/test_coupler_broadband.py
  tests/components/couplers/test_coupler_full.py
  tests/components/dies/test_align.py
  tests/components/dies/test_die.py
  tests/test_boolean.py
  tests/test_component.py
Labels: enhancement

#3682 Improve docs
  README.md
  docs/_toc.yml
  docs/workflow.md
  gdsfactory/routing/route_bundle.py
  notebooks/00_geometry.ipynb
  notebooks/04_routing.ipynb
  notebooks/09_pdk_import.ipynb
  notebooks/10_yaml_component.ipynb
  notebooks/_3_vscode.ipynb
Labels: documentation

#3686 Unpin kfactory version
  pyproject.toml
  uv.lock
Labels: bug

#3694 automatic_name_cladding_layer_sections
  gdsfactory/cross_section.py
Labels: bug
