Repository gdsfactory/gdsfactory, pull requests merged in 2025-06, with the labels that each got.

#3957 fix tests
  gdsfactory/components/pcms/litho_ruler.py
  test-data-regression/test_netlists_litho_ruler_.yml
Labels: bug

#3962 add tests for cli
  gdsfactory/cli.py
  tests/test_cli.py
Labels: enhancement, maintenance

#3970 Fix get_cross_section
  gdsfactory/components/shapes/compass.py
  gdsfactory/components/superconductors/optimal_90deg.py
  gdsfactory/path.py
  gdsfactory/pdk.py
  gdsfactory/read/from_yaml_template.py
  gdsfactory/serialization.py
  gdsfactory/snap.py
  netlist.yml
Labels: bug

#3969 improve via_stack
  gdsfactory/components/vias/via_stack.py
  gdsfactory/read/from_yaml.py
  test-data-regression/test_netlists_via_stack_.yml
  test-data-regression/test_netlists_via_stack_heater_m3_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_.yml
  test-data-regression/test_netlists_via_stack_heater_mtop_mini_.yml
  test-data-regression/test_netlists_via_stack_m1_m3_.yml
  test-data-regression/test_netlists_via_stack_m1_mtop_.yml
  test-data-regression/test_netlists_via_stack_m2_m3_.yml
  test-data-regression/test_netlists_via_stack_slab_m3_.yml
Labels: bug

#3971 Loosen return type check in get_cross_section
  Makefile
  gdsfactory/cross_section.py
  tests/test_cross_section.py
Labels: bug

#3972 add virtual_instance capabilities to schematic
  gdsfactory/read/from_yaml.py
  gdsfactory/samples/sample_array_ports.py
  gdsfactory/schematic.py
  notebooks/01_references.ipynb
Labels: enhancement, maintenance

#3983 fix netlist-tests
  .github/workflows/test_code.yml
  test-data-regression/test_netlists_awg_.yml
  test-data-regression/test_netlists_edge_coupler_array_with_loopback_.yml
  test-data-regression/test_netlists_grating_coupler_loss_.yml
  test-data-regression/test_netlists_grating_coupler_tree_.yml
  test-data-regression/test_netlists_loop_mirror_.yml
  test-data-regression/test_netlists_splitter_tree_.yml
  test-data-regression/test_netlists_switch_tree_.yml
Labels: bug

#3976 enable `get_netlist` for `ComponentAllAngle`
  gdsfactory/component.py
  gdsfactory/get_netlist.py
Labels: enhancement

#3990 Replace usage of Layers by LayerSpecs in fiducial_squares
  gdsfactory/components/shapes/fiducial_squares.py
  test-data-regression/test_netlists_fiducial_squares_.yml
  test-data-regression/test_settings_fiducial_squares_.yml
Labels: maintenance

#3989 Expose show as an argument to gds-diff in CLI
  .github/workflows/codeflash.yaml
  .pre-commit-config.yaml
  gdsfactory/cli.py
  tests/test_cli.py
Labels: maintenance

#3999 Center and fix fiducial squares when offset is an int
  gdsfactory/components/shapes/fiducial_squares.py
  test-data-regression/test_netlists_fiducial_squares_.yml
Labels: bug

#3996 update kfactory to 1.9
  gdsfactory/_cell.py
  pyproject.toml
Labels: dependencies

#3987 fix `get_netlist` with virtual cells/instances
  gdsfactory/component.py
  gdsfactory/get_netlist.py
  pyproject.toml
  test-data-regression/test_netlists_coupler_bend_.yml
  tests/test_get_netlist.py
Labels: bug

#4003 Update Superconductor Components to have "electrical" ports instead of "optical" ports
  gdsfactory/components/superconductors/optimal_90deg.py
  gdsfactory/components/superconductors/optimal_step.py
Labels: maintenance

#3985 reenable ty
  .github/workflows/test_code.yml
  gdsfactory/components/waveguides/straight.py
  gdsfactory/labels/write_test_manifest.py
  gdsfactory/path.py
Labels: github_actions

#4010 improve routing
  gdsfactory/routing/route_bundle.py
  notebooks/04_routing.ipynb
Labels: documentation

#4011 better xsection detection
  gdsfactory/cross_section.py
Labels: documentation
