Repository gdsfactory/gdsfactory, pull requests merged in 2025-07, with the labels that each got.

#4016 Import kcl within port_array
  gdsfactory/port.py
  tests/components/test_netlists.py
Labels: bug

#4030 Netlist undecorated insts
  gdsfactory/components/__init__.py
  gdsfactory/components/filters/terminator_spiral.py
  gdsfactory/components/rings/__init__.py
  gdsfactory/components/rings/ring_crow.py
  gdsfactory/get_netlist.py
  test-data-regression/test_netlists_ring_asymmetric_.yml
  test-data-regression/test_netlists_ring_crow_.yml
  test-data-regression/test_settings_ring_asymmetric_.yml
Labels: bug

#4034 propagating route_width to auto_taper in route_bundle
  gdsfactory/routing/route_bundle.py
Labels: bug

#4035 fix overloads
  gdsfactory/components/bends/bend_euler.py
Labels: bug

#4036 fix mypy
  gdsfactory/get_netlist.py
Labels: bug

#4024 Add quantum RF pcells
  gdsfactory/components/__init__.py
  gdsfactory/components/quantum/__init__.py
  gdsfactory/components/quantum/coupler_capacitive.py
  gdsfactory/components/quantum/flux_qubit.py
  gdsfactory/components/quantum/resonator.py
  gdsfactory/components/quantum/transmon.py
  test-data-regression/test_netlists_coupler_bend_.yml
  test-data-regression/test_netlists_coupler_capacitive_.yml
  test-data-regression/test_netlists_coupler_interdigital_.yml
  test-data-regression/test_netlists_coupler_tunable_.yml
  test-data-regression/test_netlists_flux_qubit_.yml
  test-data-regression/test_netlists_flux_qubit_asymmetric_.yml
  test-data-regression/test_netlists_resonator_cpw_.yml
  test-data-regression/test_netlists_resonator_lumped_.yml
  test-data-regression/test_netlists_resonator_quarter_wave_.yml
  test-data-regression/test_netlists_transmon_.yml
  test-data-regression/test_netlists_transmon_circular_.yml
  test-data-regression/test_settings_coupler_capacitive_.yml
  test-data-regression/test_settings_coupler_interdigital_.yml
  test-data-regression/test_settings_coupler_tunable_.yml
  test-data-regression/test_settings_flux_qubit_.yml
  test-data-regression/test_settings_flux_qubit_asymmetric_.yml
  test-data-regression/test_settings_resonator_cpw_.yml
  test-data-regression/test_settings_resonator_lumped_.yml
  test-data-regression/test_settings_resonator_quarter_wave_.yml
  test-data-regression/test_settings_transmon_.yml
  test-data-regression/test_settings_transmon_circular_.yml
Labels: enhancement

#4038 fix pad array size
  gdsfactory/components/pads/pad.py
  test-data-regression/test_netlists_pad_array0_.yml
  test-data-regression/test_netlists_pad_array180_.yml
  test-data-regression/test_netlists_pad_array270_.yml
  test-data-regression/test_netlists_pad_array90_.yml
  test-data-regression/test_netlists_pad_array_.yml
  test-data-regression/test_settings_pad_array_layer_.yml
  test-data-regression/test_settings_pad_array_size_.yml
  tests/components/test_components.py
Labels: bug

#4041 use place_manhattan instead of place90
  gdsfactory/routing/route_single.py
Labels: bug

#4040 Passing kwargs to connect from component_sequence
  gdsfactory/components/containers/component_sequence.py
Labels: enhancement

#4043 replace `auto_taper_taper` with `layer_transitions` in `get_bundle`
  gdsfactory/routing/auto_taper.py
  gdsfactory/routing/route_bundle.py
  tests/routing/test_routing_route_bundle_auto_taper.py
Labels: enhancement

#4049 upgrade kfactory to 1.10
  gdsfactory/_cell.py
  pyproject.toml
Labels: enhancement, dependencies

#4048 less branches inside pad_array function
  gdsfactory/components/pads/pad.py
Labels: bug

#4051 fix mypy issues
  gdsfactory/components/pads/pad.py
Labels: bug

#4053 Fix pre commit and mypy
  gdsfactory/path.py
Labels: bug

#4055 bump kfactory to 1.10.1
  pyproject.toml
Labels: dependencies

#4057 fix autotaper in fiber array routing
  gdsfactory/routing/route_bundle.py
  gdsfactory/routing/route_fiber_array.py
Labels: bug, enhancement

#4059 fix center port layer for pad with multiple bboxes
  gdsfactory/components/pads/pad.py
Labels: bug
