Repository gdsfactory/gdsfactory, pull requests merged in 2025-09, with the labels that each got.

#4143 fix spiral lengths
  gdsfactory/components/spirals/delay_snake.py
  gdsfactory/components/spirals/delay_snake2.py
  gdsfactory/components/spirals/delay_snake_sbend.py
  gdsfactory/components/spirals/spiral.py
  gdsfactory/components/spirals/spiral_inductor.py
  tests/test-data-regression/test_netlists_resonator_lumped_.yml
  tests/test-data-regression/test_settings_delay_snake2_.yml
  tests/test-data-regression/test_settings_delay_snake_.yml
  tests/test-data-regression/test_settings_delay_snake_sbend_.yml
  tests/test-data-regression/test_settings_spiral_.yml
Labels: bug

#4146 add ref off grid
  gdsfactory/component.py
  gdsfactory/components/rings/ring_pn.py
  gdsfactory/components/rings/ring_single_bend_coupler.py
  gdsfactory/components/waveguides/crossing_waveguide.py
  gdsfactory/pack.py
  gdsfactory/read/from_yaml.py
  gdsfactory/routing/route_dubins.py
  notebooks/04_routing.ipynb
  notebooks/12_grid_snapping.ipynb
  tests/test_get_netlist.py
Labels: enhancement

#4149 fix start_straight_lenght messing up routing
  gdsfactory/routing/route_bundle.py
Labels: bug

#4151 fix tests
  tests/test-data-regression/test_route_bundle_u_indirect_0_.yml
  tests/test-data-regression/test_route_bundle_u_indirect_90_.yml
Labels: bug

#4165 add_skip_cross_section_for_adding_pins
  gdsfactory/add_pins.py
Labels: maintenance

#4166 better error message
  gdsfactory/component.py
  gdsfactory/components/pcms/resistance_sheet.py
  tests/test-data-regression/test_settings_resistance_sheet_.yml
Labels: maintenance

#4167 better error message v2
  gdsfactory/component.py
Labels: maintenance

#4172 add exclude layers to write_gds and CONF
  gdsfactory/component.py
  gdsfactory/config.py
Labels: enhancement

#4181 fix wire_corner45_straight radius
  gdsfactory/components/waveguides/wire.py
  tests/test-data-regression/test_settings_wire_corner45_straight_.yml
Labels: bug

#4190 update changelog
  CHANGELOG.md
Labels: documentation, enhancement
