Repository gdsfactory/gdsfactory, pull requests merged in 2025-03, with the labels that each got.

#3698 Remove typing changes from migration docs
  notebooks/22_migration_8.ipynb
Labels: bug

#3703 update kfactory
  pyproject.toml
  uv.lock
Labels: dependencies

#3709 Allow explicit return of ComponentAllAngle in get_component
  gdsfactory/pdk.py
  gdsfactory/read/from_yaml_template.py
  uv.lock
Labels: enhancement

#3710 ignore on route colision
  gdsfactory/components/bends/bend_euler.py
  gdsfactory/routing/route_bundle.py
  pyproject.toml
  uv.lock
Labels: maintenance

#3713 Simpler spiral definition
  gdsfactory/components/spirals/spiral_heater.py
  gdsfactory/path.py
  test-data-regression/test_netlists_spiral_racetrack_heater_doped_.yml
  test-data-regression/test_settings_spiral_racetrack_.yml
  test-data-regression/test_settings_spiral_racetrack_fixed_length_.yml
  test-data-regression/test_settings_spiral_racetrack_heater_doped_.yml
  test-data-regression/test_settings_spiral_racetrack_heater_metal_.yml
Labels: enhancement

#3714 improve straight_heater
  gdsfactory/components/waveguides/straight_heater_meander.py
  gdsfactory/components/waveguides/straight_heater_meander_doped.py
  gdsfactory/pdk.py
Labels: maintenance

#3715 customize ring_double to accept gap_top and gap_top
  gdsfactory/components/rings/ring_double.py
  gdsfactory/components/rings/ring_heater.py
  gdsfactory/components/rings/ring_pn.py
  test-data-regression/test_netlists_ring_double_.yml
  test-data-regression/test_netlists_ring_double_heater_.yml
  test-data-regression/test_netlists_ring_single_heater_.yml
  test-data-regression/test_settings_ring_double_.yml
  test-data-regression/test_settings_ring_double_heater_.yml
  test-data-regression/test_settings_ring_single_heater_.yml
Labels: enhancement

#3716 fix typo
  gdsfactory/components/spirals/spiral.py
Labels: bug, maintenance

#3718 add spiral
  gdsfactory/components/__init__.py
  gdsfactory/components/filters/__init__.py
  gdsfactory/components/filters/terminator_spiral.py
  test-data-regression/test_netlists_terminator_spiral_.yml
  test-data-regression/test_settings_terminator_spiral_.yml
Labels: enhancement

#3720 Add __name__ to ComponentFunc
  gdsfactory/_cell.py
Labels: enhancement

#3723 unpin klayout
  pyproject.toml
  uv.lock
Labels: dependencies

#3725 fix sbend_offset
  gdsfactory/components/bends/bend_s.py
  test-data-regression/test_netlists_bend_s_offset_.yml
  test-data-regression/test_settings_bend_s_offset_.yml
Labels: bug, enhancement

#3726 Unbound pydantic dependency
  pyproject.toml
  uv.lock
Labels: dependencies

#3728 Fix mypy and pre-commit
  .pre-commit-config.yaml
  gdsfactory/path.py
  gdsfactory/read/from_yaml_template.py
Labels: bug

#3730 Improve ring double coupler
  gdsfactory/components/rings/ring_double.py
  test-data-regression/test_netlists_ring_double_.yml
  test-data-regression/test_settings_ring_double_.yml
Labels: documentation

#3731 add length_taper_start for mmi_tapered
  gdsfactory/components/mmis/mmi_tapered.py
  test-data-regression/test_netlists_mmi_tapered_.yml
  test-data-regression/test_settings_mmi_tapered_.yml
Labels: documentation, enhancement

#3734 improve pads
  gdsfactory/components/pads/pad.py
  gdsfactory/schematic.py
  test-data-regression/test_netlists_pad_array0_.yml
  test-data-regression/test_netlists_pad_array180_.yml
  test-data-regression/test_netlists_pad_array270_.yml
  test-data-regression/test_netlists_pad_array90_.yml
  test-data-regression/test_netlists_pad_array_.yml
  test-data-regression/test_settings_pad_array0_.yml
  test-data-regression/test_settings_pad_array180_.yml
  test-data-regression/test_settings_pad_array270_.yml
  test-data-regression/test_settings_pad_array90_.yml
  test-data-regression/test_settings_pad_array_.yml
  tests/routing/test_routing_route_bundle_west_to_north.py
Labels: documentation

#3738 fix via and add smooth to get_polygons
  .gitignore
  gdsfactory/component.py
  gdsfactory/components/vias/via_chain.py
  gdsfactory/functions.py
  test-data-regression/test_netlists_via_chain_.yml
  test-data-regression/test_settings_via_chain_.yml
  uv.lock
Labels: bug

#3739 Add get region
  gdsfactory/__init__.py
  gdsfactory/component.py
  gdsfactory/functions.py
  notebooks/00_geometry.ipynb
  notebooks/04_components_geometry.ipynb
  tests/test_component.py
Labels: enhancement

#3740 Fix Naming Error: It's "Dubins" Not "Dubin".
  gdsfactory/routing/__init__.py
  gdsfactory/routing/route_dubins.py
  notebooks/04_routing.ipynb
  tests/routing/test_route_dubins.py
Labels: documentation

#3742 add kfactory cli build command
  gdsfactory/cli.py
Labels: enhancement

#3743 bump kfactory
  pyproject.toml
Labels: dependencies

#3750 bump kfactory to 1.3
  gdsfactory/routing/route_astar.py
  gdsfactory/routing/route_bundle.py
  pyproject.toml
  test-data-regression/test_connect_bundle_u_indirect.yml
  test-data-regression/test_connect_corner.yml
  test-data-regression/test_connect_corner_A_.yml
  test-data-regression/test_connect_corner_C_.yml
  test-data-regression/test_facing_ports.yml
  test-data-regression/test_route_bundle.yml
  test-data-regression/test_route_bundle_obstacle.yml
  test-data-regression/test_route_bundle_optical.yml
  test-data-regression/test_route_bundle_optical2.yml
  test-data-regression/test_route_bundle_sort_ports.yml
  test-data-regression/test_route_bundle_u_direct_different_x.yml
  test-data-regression/test_route_bundle_u_indirect_0_.yml
  test-data-regression/test_route_bundle_u_indirect_180_.yml
  test-data-regression/test_route_bundle_u_indirect_270_.yml
  test-data-regression/test_route_bundle_u_indirect_90_.yml
  test-data-regression/test_route_bundle_udirect.yml
  test-data-regression/test_route_bundle_udirect_pads.yml
  test-data-regression/test_route_bundle_west_to_north.yml
  test-data-regression/test_route_bundle_west_to_north2.yml
  test-data-regression/test_route_connect_bundle_udirect.yml
  test-data-regression/test_route_ports_to_side.yml
  test-data-regression/test_route_ports_to_x.yml
  test-data-regression/test_route_ports_to_y.yml
  test-data-regression/test_route_single.yml
  test-data-regression/test_route_south.yml
  test-data-regression/test_settings_spiral_racetrack_fixed_length_.yml
  test-data-regression/test_settings_straight_heater_meander_.yml
  tests/read/test_component_from_yaml.py
  tests/routing/test_routing_route_bundle.py
Labels: dependencies

#3749 change_get_netlist_defaults
  gdsfactory/get_netlist.py
  test-data-regression/test_netlists_edge_coupler_array_.yml
  test-data-regression/test_netlists_edge_coupler_array_with_loopback_.yml
  test-data-regression/test_netlists_grating_coupler_loss_.yml
  test-data-regression/test_netlists_grating_coupler_tree_.yml
Labels: bug

#3747 Add coupler symmetric
  CHANGELOG.md
  gdsfactory/components/__init__.py
  gdsfactory/components/couplers/__init__.py
  test-data-regression/test_netlists_coupler_symmetric_.yml
  test-data-regression/test_settings_coupler_symmetric_.yml
Labels: bug
